$axure.loadCurrentPage({
  "url":"患者内页.html",
  "generationDate":new Date(1449523428066.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53185737ef4d43fda0ade3d3462d4cfa",
    "type":"Axure:Page",
    "name":"患者内页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"33e5ef99a8df41bcaf4fe01c6f06ac5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691944b5c4be4245b14f9d9d2f3347e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u0.png"}},
{
          "id":"b309bdefbe9c45368560c92f85b03bca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1025},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6dbd1d16a82453596e39524df3c1078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1025},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者内页/u2.png"}},
{
          "id":"db7dceb8fe794edcad194314be0179c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498dae05c96b46a2ae5d8469f3d9005c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u14.png"}},
{
          "id":"62358713cfd947d8bc58d1e4a94dc497",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":113},
            "size":{
              "width":100,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46fc0fdc15f04943b0b32a2b56548519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":113},
                "size":{
                  "width":100,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u16.png"}},
{
          "id":"2e1f61c15b854512a8a8c1ee5d762db6",
          "label":"Option 1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "mouseOver":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "selected":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":300,
              "y":137},
            "size":{
              "width":144,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4c2cdd7ed9945dfb17b8e83b60894da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "mouseOver":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "selected":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":300,
                  "y":137},
                "size":{
                  "width":144,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 Option 1 = &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2e1f61c15b854512a8a8c1ee5d762db6"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/患者内页/option_1_u8.png",
            "selected~":"images/患者内页/option_1_u8_selected.png",
            "mouseOver~":"images/患者内页/option_1_u8_mouseOver.png",
            "mouseDown~":"images/患者内页/option_1_u8_mouseDown.png",
            "disabled~":"images/患者内页/option_1_u8_mouseOver.png"}},
{
          "id":"3fd92ef24b0d4465afd01ad0ea2a5658",
          "label":"Option 5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "stateStyles":{
              "mouseOver":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "selected":{
                "fontSize":"14px",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":444,
              "y":137},
            "size":{
              "width":144,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83b09206486444b0bfed3f4495518da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "stateStyles":{
                  "mouseOver":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "selected":{
                    "fontSize":"14px",
                    "fontWeight":"bold",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":444,
                  "y":137},
                "size":{
                  "width":144,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 Option 5 = &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3fd92ef24b0d4465afd01ad0ea2a5658"]},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/患者内页/option_5_u10.png",
            "selected~":"images/患者内页/option_5_u10_selected.png",
            "mouseOver~":"images/患者内页/option_5_u10_mouseOver.png",
            "mouseDown~":"images/患者内页/option_5_u10_mouseDown.png",
            "disabled~":"images/患者内页/option_5_u10_mouseOver.png"}},
{
          "id":"eeef2d9d0a874c2189f3354606a5abbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":769,
              "y":146},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92eccbc90dad40b3ab9ccdbb28f7afb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":769,
                  "y":146},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbf898ca607045eaabefd8cb315fff31",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":137},
            "size":{
              "width":10,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者内页/u14_line.png"}},
{
          "id":"4e9edeaa30c14b2c911218a3da64cebb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":144},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12c5de994414f2283a1f230fccd7246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":144},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 医师",
                      "target":{
                        "targetType":"page",
                        "url":"医师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/现场挂号/u68.png"}},
{
          "id":"e0a5d37c0c23454e85217f4a7f185e01",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":200},
            "size":{
              "width":720,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a8577db2dbc44669160adb3705840c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a285e4671cf47999d6191dc10e4b499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u18.png"}},
{
              "id":"0e29b20cc0a24663bd78b8d75c7b1d9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe13c314036d49eb9659366a6ab203c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u30.png"}},
{
              "id":"cb767085c92e4a02992fbc0322afd91b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b9233b378e246dfba7b016142614767",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u20.png"}},
{
              "id":"6d3f6ea34d3c40edb4d760312ad32913",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"666ad875bcba4ee9a0cd877450e42013",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u32.png"}},
{
              "id":"5a996184832041ec89fb9312abd091f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":240,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31651f8582f84af1a08ea7c67478f23e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":240,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u18.png"}},
{
              "id":"a8b81975191f4f96956bf7edd78cd54c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":240,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e467748d0c6943118dbf9de54554db6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":240,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u30.png"}},
{
              "id":"cf2e6ac3089447419201618ae32c9cb0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22d7612681274ff6afb1cf919cdacdfb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u20.png"}},
{
              "id":"b62274cb8d8d42f6bc48dae9a0bb3912",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83ff014a323e4b90a339381e84d82bd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u32.png"}},
{
              "id":"2b4f335921d84b24a6bde7c288bea334",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c31d22025e94a90b67f9641fbf0726a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":480,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u18.png"}},
{
              "id":"2358ea6a84824eee9f034b34376d05e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3141153fcf97456bac45e58fba2fd4ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":480,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u30.png"}},
{
              "id":"a46b81a43f8849f0b86371917cff30d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29d289f4397547948d97a2b903bf95fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u28.png"}},
{
              "id":"def699a5c73d498484658cd71d262b27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbfa43481e664f92a4141e8b0b0f9b94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u40.png"}}]},
{
          "id":"752ecf8a13ce48a09bbf17cc08b54b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":899,
              "y":210},
            "size":{
              "width":157,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9ffed237024b34b4cd98e7903780e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":899,
                  "y":210},
                "size":{
                  "width":157,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u10.png"}},
{
          "id":"009a0ba39bca409683f24c1af2d9ecf1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":310},
            "size":{
              "width":720,
              "height":560}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b65aaae8064b2e8adae01d3041567a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b68b2bc2a0474ea8bce73ece18f7450d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u45.png"}},
{
              "id":"da89700a219441bcbfc6aa364cc1bbe3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":600,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c53309f3a9944b48cd27e011798f007",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":600,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u47.png"}},
{
              "id":"662f977c52d74f7e9d1cc352c72b55a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":120,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"630f2cea4e024903809df8af486051e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":120,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u49.png"}},
{
              "id":"5ae90fb040a84fb28e112f2ee0e4b9b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":40},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08bfbe3e62e84e89a490b5b5a51b1a8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":40},
                    "size":{
                      "width":600,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u51.png"}},
{
              "id":"8db7f7bc9f6940c5bab61e8557fe7266",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b6a81e1d2fb4211857dfc27d96ac86e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u45.png"}},
{
              "id":"39824fb61bf2479a9ecab5c93882739d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":140},
                "size":{
                  "width":600,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a10e01d8d1646cc832238f20bf522f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":140},
                    "size":{
                      "width":600,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u47.png"}},
{
              "id":"756b5ed70c2a49dab31d0630ad88cc13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3bedc38a646941939d9c7d66d9a6cd8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u45.png"}},
{
              "id":"448ac11101f14becbafbd232c5272c4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":220},
                "size":{
                  "width":600,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36c89945575a4452821d4d9958426ba1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":220},
                    "size":{
                      "width":600,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u47.png"}},
{
              "id":"4df7e17bcdc74b96ad05d35e0d3476ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dcd3d6c066649c6bd8fe8fdbd1a16d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u45.png"}},
{
              "id":"eb29ca001bea41abb737c0ee8b9e6f2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":180},
                "size":{
                  "width":600,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f9e7cd3ef234d6ba557ecbb0229773d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":180},
                    "size":{
                      "width":600,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u47.png"}},
{
              "id":"f499cdd0a64441eca44a0e688aba7580",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":120,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f7a5cfaa16f433b8c7282215f9ae502",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":260},
                    "size":{
                      "width":120,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u49.png"}},
{
              "id":"730817b9456742e1b66dab624c4331db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":260},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1397e6e72fdd4d86bbd58f22aa598bb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":260},
                    "size":{
                      "width":600,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u51.png"}},
{
              "id":"cb3d2f8739e5412d860b9caaf52f140c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":360},
                "size":{
                  "width":120,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da345b8daf5f426c9e27a9894e4e9a15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":360},
                    "size":{
                      "width":120,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u49.png"}},
{
              "id":"5b07f276873d463897e5f20247ee8046",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":360},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"186ea88c4f6041f48b96d5ea5967b5c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":360},
                    "size":{
                      "width":600,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u51.png"}},
{
              "id":"5772108f40594003a2e297ac7261207e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":460},
                "size":{
                  "width":120,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f324316631b04dee954ba7700568cd22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":460},
                    "size":{
                      "width":120,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u73.png"}},
{
              "id":"ef344d63bdcb4b67b6dedd1e725cd48a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":460},
                "size":{
                  "width":600,
                  "height":100}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41ed4af6d1b24ddd8b3af980672ce374",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":460},
                    "size":{
                      "width":600,
                      "height":100}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/患者内页/u75.png"}}]},
{
          "id":"0cc5f3fc4a6341d18374cf417c2baf2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":899,
              "y":310},
            "size":{
              "width":157,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba28ae01e66b4784b13f8ad2030635fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":899,
                  "y":310},
                "size":{
                  "width":157,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u10.png"}},
{
          "id":"11b99d943b43477aaae9106872d75a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":899,
              "y":134},
            "size":{
              "width":157,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a6b34f240741078d44753b1f3e917d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":899,
                  "y":134},
                "size":{
                  "width":157,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "33e5ef99a8df41bcaf4fe01c6f06ac5d":{
      "scriptId":"u0"},
    "691944b5c4be4245b14f9d9d2f3347e4":{
      "scriptId":"u1"},
    "b309bdefbe9c45368560c92f85b03bca":{
      "scriptId":"u2"},
    "f6dbd1d16a82453596e39524df3c1078":{
      "scriptId":"u3"},
    "db7dceb8fe794edcad194314be0179c3":{
      "scriptId":"u4"},
    "498dae05c96b46a2ae5d8469f3d9005c":{
      "scriptId":"u5"},
    "62358713cfd947d8bc58d1e4a94dc497":{
      "scriptId":"u6"},
    "46fc0fdc15f04943b0b32a2b56548519":{
      "scriptId":"u7"},
    "2e1f61c15b854512a8a8c1ee5d762db6":{
      "scriptId":"u8"},
    "c4c2cdd7ed9945dfb17b8e83b60894da":{
      "scriptId":"u9"},
    "3fd92ef24b0d4465afd01ad0ea2a5658":{
      "scriptId":"u10"},
    "83b09206486444b0bfed3f4495518da8":{
      "scriptId":"u11"},
    "eeef2d9d0a874c2189f3354606a5abbd":{
      "scriptId":"u12"},
    "92eccbc90dad40b3ab9ccdbb28f7afb5":{
      "scriptId":"u13"},
    "bbf898ca607045eaabefd8cb315fff31":{
      "scriptId":"u14"},
    "4e9edeaa30c14b2c911218a3da64cebb":{
      "scriptId":"u15"},
    "e12c5de994414f2283a1f230fccd7246":{
      "scriptId":"u16"},
    "e0a5d37c0c23454e85217f4a7f185e01":{
      "scriptId":"u17"},
    "1a8577db2dbc44669160adb3705840c7":{
      "scriptId":"u18"},
    "5a285e4671cf47999d6191dc10e4b499":{
      "scriptId":"u19"},
    "cb767085c92e4a02992fbc0322afd91b":{
      "scriptId":"u20"},
    "0b9233b378e246dfba7b016142614767":{
      "scriptId":"u21"},
    "5a996184832041ec89fb9312abd091f9":{
      "scriptId":"u22"},
    "31651f8582f84af1a08ea7c67478f23e":{
      "scriptId":"u23"},
    "cf2e6ac3089447419201618ae32c9cb0":{
      "scriptId":"u24"},
    "22d7612681274ff6afb1cf919cdacdfb":{
      "scriptId":"u25"},
    "2b4f335921d84b24a6bde7c288bea334":{
      "scriptId":"u26"},
    "3c31d22025e94a90b67f9641fbf0726a":{
      "scriptId":"u27"},
    "a46b81a43f8849f0b86371917cff30d5":{
      "scriptId":"u28"},
    "29d289f4397547948d97a2b903bf95fe":{
      "scriptId":"u29"},
    "0e29b20cc0a24663bd78b8d75c7b1d9f":{
      "scriptId":"u30"},
    "fe13c314036d49eb9659366a6ab203c8":{
      "scriptId":"u31"},
    "6d3f6ea34d3c40edb4d760312ad32913":{
      "scriptId":"u32"},
    "666ad875bcba4ee9a0cd877450e42013":{
      "scriptId":"u33"},
    "a8b81975191f4f96956bf7edd78cd54c":{
      "scriptId":"u34"},
    "e467748d0c6943118dbf9de54554db6f":{
      "scriptId":"u35"},
    "b62274cb8d8d42f6bc48dae9a0bb3912":{
      "scriptId":"u36"},
    "83ff014a323e4b90a339381e84d82bd6":{
      "scriptId":"u37"},
    "2358ea6a84824eee9f034b34376d05e4":{
      "scriptId":"u38"},
    "3141153fcf97456bac45e58fba2fd4ba":{
      "scriptId":"u39"},
    "def699a5c73d498484658cd71d262b27":{
      "scriptId":"u40"},
    "dbfa43481e664f92a4141e8b0b0f9b94":{
      "scriptId":"u41"},
    "752ecf8a13ce48a09bbf17cc08b54b65":{
      "scriptId":"u42"},
    "3f9ffed237024b34b4cd98e7903780e9":{
      "scriptId":"u43"},
    "009a0ba39bca409683f24c1af2d9ecf1":{
      "scriptId":"u44"},
    "d9b65aaae8064b2e8adae01d3041567a":{
      "scriptId":"u45"},
    "b68b2bc2a0474ea8bce73ece18f7450d":{
      "scriptId":"u46"},
    "da89700a219441bcbfc6aa364cc1bbe3":{
      "scriptId":"u47"},
    "2c53309f3a9944b48cd27e011798f007":{
      "scriptId":"u48"},
    "662f977c52d74f7e9d1cc352c72b55a1":{
      "scriptId":"u49"},
    "630f2cea4e024903809df8af486051e2":{
      "scriptId":"u50"},
    "5ae90fb040a84fb28e112f2ee0e4b9b6":{
      "scriptId":"u51"},
    "08bfbe3e62e84e89a490b5b5a51b1a8d":{
      "scriptId":"u52"},
    "8db7f7bc9f6940c5bab61e8557fe7266":{
      "scriptId":"u53"},
    "5b6a81e1d2fb4211857dfc27d96ac86e":{
      "scriptId":"u54"},
    "39824fb61bf2479a9ecab5c93882739d":{
      "scriptId":"u55"},
    "5a10e01d8d1646cc832238f20bf522f2":{
      "scriptId":"u56"},
    "4df7e17bcdc74b96ad05d35e0d3476ef":{
      "scriptId":"u57"},
    "6dcd3d6c066649c6bd8fe8fdbd1a16d1":{
      "scriptId":"u58"},
    "eb29ca001bea41abb737c0ee8b9e6f2d":{
      "scriptId":"u59"},
    "3f9e7cd3ef234d6ba557ecbb0229773d":{
      "scriptId":"u60"},
    "756b5ed70c2a49dab31d0630ad88cc13":{
      "scriptId":"u61"},
    "3bedc38a646941939d9c7d66d9a6cd8a":{
      "scriptId":"u62"},
    "448ac11101f14becbafbd232c5272c4c":{
      "scriptId":"u63"},
    "36c89945575a4452821d4d9958426ba1":{
      "scriptId":"u64"},
    "f499cdd0a64441eca44a0e688aba7580":{
      "scriptId":"u65"},
    "2f7a5cfaa16f433b8c7282215f9ae502":{
      "scriptId":"u66"},
    "730817b9456742e1b66dab624c4331db":{
      "scriptId":"u67"},
    "1397e6e72fdd4d86bbd58f22aa598bb7":{
      "scriptId":"u68"},
    "cb3d2f8739e5412d860b9caaf52f140c":{
      "scriptId":"u69"},
    "da345b8daf5f426c9e27a9894e4e9a15":{
      "scriptId":"u70"},
    "5b07f276873d463897e5f20247ee8046":{
      "scriptId":"u71"},
    "186ea88c4f6041f48b96d5ea5967b5c6":{
      "scriptId":"u72"},
    "5772108f40594003a2e297ac7261207e":{
      "scriptId":"u73"},
    "f324316631b04dee954ba7700568cd22":{
      "scriptId":"u74"},
    "ef344d63bdcb4b67b6dedd1e725cd48a":{
      "scriptId":"u75"},
    "41ed4af6d1b24ddd8b3af980672ce374":{
      "scriptId":"u76"},
    "0cc5f3fc4a6341d18374cf417c2baf2c":{
      "scriptId":"u77"},
    "ba28ae01e66b4784b13f8ad2030635fa":{
      "scriptId":"u78"},
    "11b99d943b43477aaae9106872d75a06":{
      "scriptId":"u79"},
    "06a6b34f240741078d44753b1f3e917d":{
      "scriptId":"u80"}}});