$axure.loadCurrentPage({
  "url":"预约取号.html",
  "generationDate":new Date(1450315459184.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"024a441541ea46bb94474dfb689329c3",
    "type":"Axure:Page",
    "name":"预约取号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cfd4ce9862d042369058ab5ff151a3b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c739b5218cc648bb89e7fe48e300aee8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u0.png"}},
{
          "id":"b7b74b74ef794fd085a78d9d2d403d0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1026},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e588464818e64016a132d814c5596690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1026},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u2.png"}},
{
          "id":"49df4cc377cc4f9f9cdf85f0961f4082",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1062},
            "size":{
              "width":769,
              "height":77},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d54761955e4416f9f161dcf704b302c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1062},
                "size":{
                  "width":769,
                  "height":77},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u8.png"}},
{
          "id":"c2d7d68f0d444423a433ec2ad390ae45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a230f2ff2a841b6893e8cff3ff7b2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u10.png"}},
{
          "id":"68405c229e714c3cb40cdec7c45bddcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":113},
            "size":{
              "width":100,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4110af58ac4fb3b112777bc0a9b6a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":113},
                "size":{
                  "width":100,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u12.png"}},
{
          "id":"9ea9a14174f543c38397573969481911",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":408,
              "y":143},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"734137a536d947c2ad41c82b888ace18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":408,
                  "y":143},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58fa82f8a3c640faacf2db0e2c0d43fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":1090},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19cd0f0a825545abba313e78efc6ff44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":1090},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u16.png"}},
{
          "id":"7ea975f4ce8447f8bba0e43c3b0eb4c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":418,
              "y":1119},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4f002989ce4039bb2f0c92f282aa72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":418,
                  "y":1119},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e58f429d64f41a49565928b3f4fc503",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":144},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece17fe7ddb149deb6e0bdf30bb3d019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":144},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入预约信息",
                      "target":{
                        "targetType":"page",
                        "url":"输入预约信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/输入个人信息/u16.png"}},
{
          "id":"bcc3d2931471431bbb57d3c027d36dd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":330},
            "size":{
              "width":600,
              "height":370},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae3b2ab201f4231865636fa5b7e7d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":330},
                "size":{
                  "width":600,
                  "height":370},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入个人信息/u19.png"}},
{
          "id":"b0ed84277cd549ff9744a3a741ce061c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":412,
              "y":352},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d0e9ba65acd4e5586b6bcb86350d720",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":412,
                  "y":352},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"427385fb1c564ce7bca3bb0e35b21626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "lineSpacing":"36px",
            "location":{
              "x":240,
              "y":400},
            "size":{
              "width":410,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29a59a5d88c2459da934a6f2812f0803",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "lineSpacing":"36px",
                "location":{
                  "x":240,
                  "y":400},
                "size":{
                  "width":410,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c635f587f95a47cc9ce709d2ff5643b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":240,
              "y":622},
            "size":{
              "width":410,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"17e3ab9b15ca4997ad6100af3d730cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":511},
            "size":{
              "width":270,
              "height":179},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18128f179236430599f967b56378296c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":511},
                "size":{
                  "width":270,
                  "height":179},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u80.png"}},
{
          "id":"5ce416f2b5644859b81296ced19d43c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":642},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择医师和时间/u82_line.png"}},
{
          "id":"7a58a505d9454465bc4d0cc066674fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"center",
            "location":{
              "x":1044,
              "y":541},
            "size":{
              "width":243,
              "height":72},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cabfdb5c6721479890d8c160d0c532e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "location":{
                  "x":1044,
                  "y":541},
                "size":{
                  "width":243,
                  "height":72},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9d548c95efa471b94b8b896762418c0",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1125,
              "y":657},
            "size":{
              "width":81,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1767307d376841719cb151b66b12bb5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1125,
                  "y":657},
                "size":{
                  "width":81,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f31bb0351794a6291bd35d87a35171b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06112972acd24e6699d0d55c136c5fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "cfd4ce9862d042369058ab5ff151a3b7":{
      "scriptId":"u0"},
    "c739b5218cc648bb89e7fe48e300aee8":{
      "scriptId":"u1"},
    "b7b74b74ef794fd085a78d9d2d403d0c":{
      "scriptId":"u2"},
    "e588464818e64016a132d814c5596690":{
      "scriptId":"u3"},
    "49df4cc377cc4f9f9cdf85f0961f4082":{
      "scriptId":"u4"},
    "8d54761955e4416f9f161dcf704b302c":{
      "scriptId":"u5"},
    "c2d7d68f0d444423a433ec2ad390ae45":{
      "scriptId":"u6"},
    "7a230f2ff2a841b6893e8cff3ff7b2bb":{
      "scriptId":"u7"},
    "68405c229e714c3cb40cdec7c45bddcc":{
      "scriptId":"u8"},
    "4c4110af58ac4fb3b112777bc0a9b6a4":{
      "scriptId":"u9"},
    "9ea9a14174f543c38397573969481911":{
      "scriptId":"u10"},
    "734137a536d947c2ad41c82b888ace18":{
      "scriptId":"u11"},
    "58fa82f8a3c640faacf2db0e2c0d43fa":{
      "scriptId":"u12"},
    "19cd0f0a825545abba313e78efc6ff44":{
      "scriptId":"u13"},
    "7ea975f4ce8447f8bba0e43c3b0eb4c8":{
      "scriptId":"u14"},
    "1f4f002989ce4039bb2f0c92f282aa72":{
      "scriptId":"u15"},
    "3e58f429d64f41a49565928b3f4fc503":{
      "scriptId":"u16"},
    "ece17fe7ddb149deb6e0bdf30bb3d019":{
      "scriptId":"u17"},
    "bcc3d2931471431bbb57d3c027d36dd0":{
      "scriptId":"u18"},
    "4ae3b2ab201f4231865636fa5b7e7d13":{
      "scriptId":"u19"},
    "b0ed84277cd549ff9744a3a741ce061c":{
      "scriptId":"u20"},
    "1d0e9ba65acd4e5586b6bcb86350d720":{
      "scriptId":"u21"},
    "427385fb1c564ce7bca3bb0e35b21626":{
      "scriptId":"u22"},
    "29a59a5d88c2459da934a6f2812f0803":{
      "scriptId":"u23"},
    "c635f587f95a47cc9ce709d2ff5643b1":{
      "scriptId":"u24"},
    "17e3ab9b15ca4997ad6100af3d730cb1":{
      "scriptId":"u25"},
    "18128f179236430599f967b56378296c":{
      "scriptId":"u26"},
    "5ce416f2b5644859b81296ced19d43c2":{
      "scriptId":"u27"},
    "7a58a505d9454465bc4d0cc066674fe3":{
      "scriptId":"u28"},
    "cabfdb5c6721479890d8c160d0c532e0":{
      "scriptId":"u29"},
    "a9d548c95efa471b94b8b896762418c0":{
      "scriptId":"u30"},
    "1767307d376841719cb151b66b12bb5c":{
      "scriptId":"u31"},
    "8f31bb0351794a6291bd35d87a35171b":{
      "scriptId":"u32"},
    "06112972acd24e6699d0d55c136c5fac":{
      "scriptId":"u33"}}});