$axure.loadCurrentPage({
  "url":"患者队列_2.html",
  "generationDate":new Date(1451163293547.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"33f990be8b2e4f62a71654dafa9bee24",
    "type":"Axure:Page",
    "name":"患者队列",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"17d4288588364042a3378e657f9fb7a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcf5f26854a34a0d9fb0c0da41d34c50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u0.png"}},
{
          "id":"378ed61770034d3eb1d5844c3c30b457",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1026},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe8f0c0d541442db9db718fb06a413ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1026},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列_1/u2.png"}},
{
          "id":"0d8e35f6c4024e7eb7ddcc5a60d5ace4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1062},
            "size":{
              "width":769,
              "height":77},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5f22af69fb64f15bd3896a6a7e192eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1062},
                "size":{
                  "width":769,
                  "height":77},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u8.png"}},
{
          "id":"25a8615e72b1490caf2c5ed9a6f6e895",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":235,
              "y":1119},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e141208a11704be59c302369c82f5545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":1119},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50cb5258065e46278a3b11991f377915",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":1092},
            "size":{
              "width":25,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eabd9fa2b6c4b9fb99177855f8daac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":1092},
                "size":{
                  "width":25,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u8.png"}},
{
          "id":"0ca0ccf92dce4658923678266546b54e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":598,
              "y":1119},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d454e763f854355af9a354cd2ef4a2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":598,
                  "y":1119},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ecbafa116c044f5911460f1245357df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":1085},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243275dd53044ea5aeccac1688aaccf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":1085},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u14.png"}},
{
          "id":"50d25d6c74e44ab49dccd8c7198e3b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":75,
              "y":221},
            "size":{
              "width":156,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a986a1a5a4f84fb696615d2512398a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":221},
                "size":{
                  "width":156,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b69fac2afcd649f08aa0fe0f81a0e6b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":265},
            "size":{
              "width":156,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b8619f01bc4a83b96ffe7fe905a671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":265},
                "size":{
                  "width":156,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d564efeca56545f2a85d6f1e66a0a612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":309},
            "size":{
              "width":156,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379ea852d17d407782aadc51044242f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":309},
                "size":{
                  "width":156,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a5345fb9d3b4e1ea163de3ddbefa245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":352},
            "size":{
              "width":156,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3c1fc332c114b72a20a87d18b10a1d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":352},
                "size":{
                  "width":156,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af9f98e34bd94685bbd9fc2af8ab604f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":300,
              "y":220},
            "size":{
              "width":31,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac2952148d914b4aa9ae223c11571397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":220},
                "size":{
                  "width":31,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d885bf5b963541c7b69c26e3d26f3b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":292,
              "y":264},
            "size":{
              "width":39,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0d17608d6d446329f4a949b3e8932eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":264},
                "size":{
                  "width":39,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e78ef315b49742c292429901342814aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":308},
            "size":{
              "width":31,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2ade867433f4ecd87aa4bb35de99740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":308},
                "size":{
                  "width":31,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71c1501e31f642f9a18436aaced3809a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":352},
            "size":{
              "width":31,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5651f42e0a74541b1296955789b3ffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":352},
                "size":{
                  "width":31,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b30ab044f2954cf2a9dd36c739ee02cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":262},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70bf2a25f67b405fbf1747c8a0fec3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":262},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户预约（微信）/u16.png"}},
{
          "id":"eb07e97197d64f9598a26105c876a2d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":307},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8cb70f7faea48bfbd4151743e890dec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":307},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u32.png"}},
{
          "id":"93bff7e73f04443d921f6fa03b107379",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":351},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4d48b2eed747c0ae4275fd545d7482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":351},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u32.png"}},
{
          "id":"cac0bc9efad94d6c872c9ec64bfb4ae4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":221},
            "size":{
              "width":141,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d90c7bf29bce4354972a8319bf051965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":221},
                "size":{
                  "width":141,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"911d560c35da446db48a3fd5aa085dcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":264},
            "size":{
              "width":141,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d545bc86444264b08a4915badc5376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":264},
                "size":{
                  "width":141,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a7061241ee742c9a14ffeaeb58cb63e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":308},
            "size":{
              "width":125,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c8bb05998884ee18d879c649fcb421e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":308},
                "size":{
                  "width":125,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28c3d8f5104448ea947209ecf53b4aca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":351},
            "size":{
              "width":141,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46723bd64aac476ab400fda0a649b206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":351},
                "size":{
                  "width":141,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd8ca9cd757646209a59c574c9c8540e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":394},
            "size":{
              "width":152,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aa0197f1760445cae7cc3eb1539c823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":394},
                "size":{
                  "width":152,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26594f333a35415c8f6e78aad29d864e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":437},
            "size":{
              "width":141,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"396657d7365a47ea9eb2a50f2004ae16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":437},
                "size":{
                  "width":141,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c1055e48d28421096352882afb44e8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":481},
            "size":{
              "width":141,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ee83a8157c4f99b7d3b4625b87877a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":481},
                "size":{
                  "width":141,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"993ce0c9e1444901b424200bcb977896",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":404,
              "y":524},
            "size":{
              "width":125,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c813ae57cf4f79ade0f4c7a4539bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":404,
                  "y":524},
                "size":{
                  "width":125,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb81f39892d24619b891864bbdb8b006",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":143},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcbdea97738248f9aa03f0ff5113383a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":143},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7171b2c785a14bee99e944c5a1e4998d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":551,
              "y":143},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"242ad443ed3d48e7a1c8a362632ecf46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":551,
                  "y":143},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48a67299440446d898f25820db285b90",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":206},
            "size":{
              "width":411,
              "height":48}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 治疗记录",
                      "target":{
                        "targetType":"page",
                        "url":"治疗记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "17d4288588364042a3378e657f9fb7a7":{
      "scriptId":"u0"},
    "dcf5f26854a34a0d9fb0c0da41d34c50":{
      "scriptId":"u1"},
    "378ed61770034d3eb1d5844c3c30b457":{
      "scriptId":"u2"},
    "fe8f0c0d541442db9db718fb06a413ff":{
      "scriptId":"u3"},
    "0d8e35f6c4024e7eb7ddcc5a60d5ace4":{
      "scriptId":"u4"},
    "a5f22af69fb64f15bd3896a6a7e192eb":{
      "scriptId":"u5"},
    "25a8615e72b1490caf2c5ed9a6f6e895":{
      "scriptId":"u6"},
    "e141208a11704be59c302369c82f5545":{
      "scriptId":"u7"},
    "50cb5258065e46278a3b11991f377915":{
      "scriptId":"u8"},
    "2eabd9fa2b6c4b9fb99177855f8daac7":{
      "scriptId":"u9"},
    "0ca0ccf92dce4658923678266546b54e":{
      "scriptId":"u10"},
    "4d454e763f854355af9a354cd2ef4a2a":{
      "scriptId":"u11"},
    "5ecbafa116c044f5911460f1245357df":{
      "scriptId":"u12"},
    "243275dd53044ea5aeccac1688aaccf8":{
      "scriptId":"u13"},
    "50d25d6c74e44ab49dccd8c7198e3b91":{
      "scriptId":"u14"},
    "a986a1a5a4f84fb696615d2512398a02":{
      "scriptId":"u15"},
    "b69fac2afcd649f08aa0fe0f81a0e6b2":{
      "scriptId":"u16"},
    "34b8619f01bc4a83b96ffe7fe905a671":{
      "scriptId":"u17"},
    "d564efeca56545f2a85d6f1e66a0a612":{
      "scriptId":"u18"},
    "379ea852d17d407782aadc51044242f6":{
      "scriptId":"u19"},
    "8a5345fb9d3b4e1ea163de3ddbefa245":{
      "scriptId":"u20"},
    "a3c1fc332c114b72a20a87d18b10a1d1":{
      "scriptId":"u21"},
    "af9f98e34bd94685bbd9fc2af8ab604f":{
      "scriptId":"u22"},
    "ac2952148d914b4aa9ae223c11571397":{
      "scriptId":"u23"},
    "d885bf5b963541c7b69c26e3d26f3b4a":{
      "scriptId":"u24"},
    "d0d17608d6d446329f4a949b3e8932eb":{
      "scriptId":"u25"},
    "e78ef315b49742c292429901342814aa":{
      "scriptId":"u26"},
    "e2ade867433f4ecd87aa4bb35de99740":{
      "scriptId":"u27"},
    "71c1501e31f642f9a18436aaced3809a":{
      "scriptId":"u28"},
    "d5651f42e0a74541b1296955789b3ffc":{
      "scriptId":"u29"},
    "b30ab044f2954cf2a9dd36c739ee02cb":{
      "scriptId":"u30"},
    "70bf2a25f67b405fbf1747c8a0fec3dd":{
      "scriptId":"u31"},
    "eb07e97197d64f9598a26105c876a2d1":{
      "scriptId":"u32"},
    "f8cb70f7faea48bfbd4151743e890dec":{
      "scriptId":"u33"},
    "93bff7e73f04443d921f6fa03b107379":{
      "scriptId":"u34"},
    "fc4d48b2eed747c0ae4275fd545d7482":{
      "scriptId":"u35"},
    "cac0bc9efad94d6c872c9ec64bfb4ae4":{
      "scriptId":"u36"},
    "d90c7bf29bce4354972a8319bf051965":{
      "scriptId":"u37"},
    "911d560c35da446db48a3fd5aa085dcc":{
      "scriptId":"u38"},
    "56d545bc86444264b08a4915badc5376":{
      "scriptId":"u39"},
    "2a7061241ee742c9a14ffeaeb58cb63e":{
      "scriptId":"u40"},
    "6c8bb05998884ee18d879c649fcb421e":{
      "scriptId":"u41"},
    "28c3d8f5104448ea947209ecf53b4aca":{
      "scriptId":"u42"},
    "46723bd64aac476ab400fda0a649b206":{
      "scriptId":"u43"},
    "fd8ca9cd757646209a59c574c9c8540e":{
      "scriptId":"u44"},
    "4aa0197f1760445cae7cc3eb1539c823":{
      "scriptId":"u45"},
    "26594f333a35415c8f6e78aad29d864e":{
      "scriptId":"u46"},
    "396657d7365a47ea9eb2a50f2004ae16":{
      "scriptId":"u47"},
    "5c1055e48d28421096352882afb44e8d":{
      "scriptId":"u48"},
    "40ee83a8157c4f99b7d3b4625b87877a":{
      "scriptId":"u49"},
    "993ce0c9e1444901b424200bcb977896":{
      "scriptId":"u50"},
    "d3c813ae57cf4f79ade0f4c7a4539bac":{
      "scriptId":"u51"},
    "fb81f39892d24619b891864bbdb8b006":{
      "scriptId":"u52"},
    "fcbdea97738248f9aa03f0ff5113383a":{
      "scriptId":"u53"},
    "7171b2c785a14bee99e944c5a1e4998d":{
      "scriptId":"u54"},
    "242ad443ed3d48e7a1c8a362632ecf46":{
      "scriptId":"u55"},
    "48a67299440446d898f25820db285b90":{
      "scriptId":"u56"}}});