$axure.loadCurrentPage({
  "url":"单据打印.html",
  "generationDate":new Date(1450315460205.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"38b7b06bbe87484cb2a8b35366504d85",
    "type":"Axure:Page",
    "name":"单据打印",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e250cf42e1294a3dae38a29ff47747c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":30},
            "size":{
              "width":640,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ace0f1bc534497eb060f59aaec1d73e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":30},
                "size":{
                  "width":640,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u0.png"}},
{
          "id":"b6c594ded71f4f4091e1157bc5c8c2da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":306,
              "y":50},
            "size":{
              "width":181,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"348c06a0ff7d40e1834cf68bced1b86f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":306,
                  "y":50},
                "size":{
                  "width":181,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f970d49116448aa8eb459db3b79b098",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":94},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77575d9cffa54e30841bb5ca5013d178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":94},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7e8f03d1ebd48e081da789ed5bad6f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":270,
              "y":94},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3288ea8397044c9e839ee1bde8bd68fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":270,
                  "y":94},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9bf15559bc14b438724459bbb92623f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":391,
              "y":94},
            "size":{
              "width":67,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235cd3fcc1324702983714594a80424a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":391,
                  "y":94},
                "size":{
                  "width":67,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae99223fd0bc4e6e852dcbde69f2ae0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":410,
              "y":259},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda413be06fb4ade8b1abe0638bdb945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":410,
                  "y":259},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75df2edd100341ac9920cf3d58210a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":533,
              "y":259},
            "size":{
              "width":135,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ceff9aae4e24402a3f5ca83d0d1d990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":533,
                  "y":259},
                "size":{
                  "width":135,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f17581f714424ceb8117c8d3ff030127",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":513,
              "y":94},
            "size":{
              "width":144,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a736ffc9364d4882da53c851d35651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":513,
                  "y":94},
                "size":{
                  "width":144,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41503ee044b24b188c2e7d1a5c41eb2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":130},
            "size":{
              "width":558,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14aed93d7f54933a83ccbc61c62022d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":130},
                "size":{
                  "width":558,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u16.png"}},
{
          "id":"b542206497b8473ca8e2d2adcff4f749",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":144},
            "size":{
              "width":49,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b67697d992b4c5dae32f745c4d1c2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":144},
                "size":{
                  "width":49,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"535ad160f7d1463d820019ad81171f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":260,
              "y":174},
            "size":{
              "width":257,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"740da0f2686d4233890ae8a5c6220aae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":260,
                  "y":174},
                "size":{
                  "width":257,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2259e958117c42cd8b5cc3a83455fbc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":800,
              "y":130},
            "size":{
              "width":220,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"603354b0b7764699aae5609e9a1603fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":800,
                  "y":130},
                "size":{
                  "width":220,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者内页/u36.png"}},
{
          "id":"e7cde3668f4a45b1ad4aa755d10673e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":800,
              "y":495},
            "size":{
              "width":220,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b779424371ea47e98078c5c1705f4b8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":800,
                  "y":495},
                "size":{
                  "width":220,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者内页/u36.png"}},
{
          "id":"a935db9b3361454ebc0c1c4997950ef5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":360},
            "size":{
              "width":640,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1525be1a80354cabae1db94a4a0b2657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":360},
                "size":{
                  "width":640,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u26.png"}},
{
          "id":"599bc0aa899a4484bde196ec75bd80c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":319.5,
              "y":380},
            "size":{
              "width":141,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1420c6d08db04953b87b0aa78c4e8a9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":319.5,
                  "y":380},
                "size":{
                  "width":141,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e180ea60105454d8ee13a18bfde7c5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":424},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0037d36beb24fc387416ddf07aa563d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":424},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4fbbe2c26074c4daa473f966702e884",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":270,
              "y":424},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f50c8ec2fa4e02b67ccb01e053a565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":270,
                  "y":424},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd24f92ba37d4a9e8f1de96ab20e8600",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":391,
              "y":424},
            "size":{
              "width":67,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387064ee99d04099ab1b738eef0df322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":391,
                  "y":424},
                "size":{
                  "width":67,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a10288f2cc4160ad18e08b09a61bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":410,
              "y":740},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cb848eda7c74385bee5bbd20b4acd84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":410,
                  "y":740},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a17891569da4eb6be9ff07e5f78ca8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":533,
              "y":740},
            "size":{
              "width":135,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16a04eb70984f11b196c9644c6b8443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":533,
                  "y":740},
                "size":{
                  "width":135,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbd25a2599064f5da50cf3f87bcbcf11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":513,
              "y":424},
            "size":{
              "width":144,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab39ced7b3ab462ea5786186f8b50a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":513,
                  "y":424},
                "size":{
                  "width":144,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f14e50d4e98e40e0b4887a57b402cbd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":495},
            "size":{
              "width":558,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d063ca963d5f4c6385fd02c06fc444b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":495},
                "size":{
                  "width":558,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u42.png"}},
{
          "id":"53341c08273640c3b9ce6b7915c50ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":509},
            "size":{
              "width":37,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57efd82fd5924adfb9a124fbd809e877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":509},
                "size":{
                  "width":37,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2d7400e7ce7497b82e54ab80a3bd3bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":549},
            "size":{
              "width":66,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed9946e5b9c2418ab6bf84a261896fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":549},
                "size":{
                  "width":66,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"783abe926deb45b9b7ff8066eb9346fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":44},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec95193f90e84420b3eddf64340d9ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":44},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cc6c765a6534904b230a1d585b7a658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":370},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8a0b211d0f041efafc88da696556b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":370},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0604865687f54954a5a9951b57f8a1ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":455},
            "size":{
              "width":161,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8a5af4fd3164c5692c225917a7b15a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":455},
                "size":{
                  "width":161,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25575000f9a54cde9c6ea9b27d4e6c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":223,
              "y":549},
            "size":{
              "width":66,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af64839fe254fb3a85a739073184af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":223,
                  "y":549},
                "size":{
                  "width":66,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"021262e6df664d218ef50b8b9affafa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":329,
              "y":549},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3509ea5528e0438aba65b5c50cef68ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":329,
                  "y":549},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b104764d3224fd28b88c4e8a82ac155",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":549},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0299a6911e6344e882465cb29eb526aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":549},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567b08a9e33b4ece87de8d42f54c2a1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":571,
              "y":549},
            "size":{
              "width":57,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d3b1824e7974023ac1089bccc122428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":571,
                  "y":549},
                "size":{
                  "width":57,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e68cc2b3f2964222ab4072b3531d1faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":580},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a15faf1c466b4d98a8bc906ba58d4e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":580},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b887a95f5b744e1a7b2534e23ee36af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":223,
              "y":580},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77a67e38fa5a4eea836a6c7b44506115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":223,
                  "y":580},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3043a9fb1ad64767a2e5d4abd12559f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":329,
              "y":580},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d87cf082824a4a4d87c2c4fb1626e182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":329,
                  "y":580},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7c6424bef3d43bca6593f179c5264d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":580},
            "size":{
              "width":66,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74ad864786974113888e9216a7eceefe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":580},
                "size":{
                  "width":66,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78df47a88ddd444abe28c53c3fd26880",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":571,
              "y":580},
            "size":{
              "width":66,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b07aca2f05cd41949bf7757e94b7212d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":571,
                  "y":580},
                "size":{
                  "width":66,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6813d8a5aea4ac3abc222e472fd587a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":611},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb17a42b3b664cbb88e11719614ce52e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":611},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a5cd628f19c4831b08b2dcc0cba71d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":223,
              "y":611},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03452ff3edd4ecebec1f5170776bbb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":223,
                  "y":611},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54475987bcf54fa6b1440195885fe60b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":329,
              "y":611},
            "size":{
              "width":82,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b4c3a02eb644118994320e8ee7d783",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":329,
                  "y":611},
                "size":{
                  "width":82,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec10b26df1c449d3b2144de3ad659918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":600,
              "y":670},
            "size":{
              "width":40,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c211edd9514aa2b2b82542dcb7ee3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":600,
                  "y":670},
                "size":{
                  "width":40,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f143fb5e7c9043fab4ea4fa18b34a47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":840},
            "size":{
              "width":640,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"987cf6b9649149f09488a41106c42adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":840},
                "size":{
                  "width":640,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u26.png"}},
{
          "id":"95564d052e494d92832369396f6ee84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":320,
              "y":860},
            "size":{
              "width":141,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e647a570d65b41a8b89973fa2c0c6b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":320,
                  "y":860},
                "size":{
                  "width":141,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71636e6f87c047f4ad90e3d141c820d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":904},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd3fbf5203d142fda4ebb5ea76f3dd36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":904},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd3ddb2e5d84b018252f7b23cbe625d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":270,
              "y":904},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66f21eca6386435688fba5d144411165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":270,
                  "y":904},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a58f9d8f34a14b35ae8ec3651776e0f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":391,
              "y":904},
            "size":{
              "width":67,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df13e2f6d7544e19b5019545f9bb2312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":391,
                  "y":904},
                "size":{
                  "width":67,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ecab6e8eaf4319b2226261f762aa65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":410,
              "y":1220},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c35ccfb1bb044fe9aea26a4dfda40883",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":410,
                  "y":1220},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe50b657d3334d10a8831b74c0e56488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":533,
              "y":1220},
            "size":{
              "width":135,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04858c2ceecb4cd7ae9f1f163ff164f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":533,
                  "y":1220},
                "size":{
                  "width":135,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff08888455584b9ca319d8fcf2818efb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":513,
              "y":904},
            "size":{
              "width":144,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52fe925ea0c84c29859a2a0a5348720d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":513,
                  "y":904},
                "size":{
                  "width":144,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41b3ff8d95604163ae9edeff508a9e88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":975},
            "size":{
              "width":558,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b480297d35394d6e97e4e8b122f56c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":975},
                "size":{
                  "width":558,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/单据打印/u42.png"}},
{
          "id":"1c5e99b6e49942ac8c8ddccd4eac627b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":989},
            "size":{
              "width":37,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3821773a745b4d57b572e748a2fae75b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":989},
                "size":{
                  "width":37,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e33af7737f864364b52dc821ce875b9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":850},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2710b193b31a4c77a1b6d4985fe4f468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":850},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9987ac8509794a97a4d1e835d054cf1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":118,
              "y":935},
            "size":{
              "width":113,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7d09845e3d543f8a9190c92f90c9cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":118,
                  "y":935},
                "size":{
                  "width":113,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35bb378fca194e92a145b6bf45942e07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":800,
              "y":930},
            "size":{
              "width":220,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439507ec2e7f47eab1dbdf9edd97bea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":800,
                  "y":930},
                "size":{
                  "width":220,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者内页/u36.png"}},
{
          "id":"9a841a5db27b42d28b4eeb373f5bc2e1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":1029},
            "size":{
              "width":537,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f0a3f5b1ea048128025396d141e34ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "size":{
                  "width":69,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24beed00a0cf4e80b0856e7b3dd2e565",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "size":{
                      "width":69,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u107.png"}},
{
              "id":"080b4f2db92e42ae8c49824c0a97d2a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":69,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"496eec27ca1e41cfa7d7a8b769486958",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":69,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u115.png"}},
{
              "id":"a5751d0e9d5e4f31a372c461e0b7e504",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":69,
                  "y":0},
                "size":{
                  "width":225,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e2bb3cebafb4f2daf821cf87bad378e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":69,
                      "y":0},
                    "size":{
                      "width":225,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u109.png"}},
{
              "id":"26129e5bec7e45ac930a07b13201338a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":69,
                  "y":60},
                "size":{
                  "width":225,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b27f01098c9e4f219acc059e5faa1097",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":69,
                      "y":60},
                    "size":{
                      "width":225,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u117.png"}},
{
              "id":"453ec0c970ea4d27925fcd7caae1374a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":121,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea15a1ccee8e4758998df507653a4ed7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":121,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u111.png"}},
{
              "id":"726dab6e797e406287c4d3f61b9c7d50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":294,
                  "y":60},
                "size":{
                  "width":121,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77ef56b616a64489aa4a1a30bf41a224",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":294,
                      "y":60},
                    "size":{
                      "width":121,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u119.png"}},
{
              "id":"3876daca082044148c4c945a768a4923",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":415,
                  "y":0},
                "size":{
                  "width":122,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"698b456d0b484ad5a0544721fb26ad37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":415,
                      "y":0},
                    "size":{
                      "width":122,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u113.png"}},
{
              "id":"188606b216744f33ad703471b92dd6f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":415,
                  "y":60},
                "size":{
                  "width":122,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d3397a82c534f19a43647eedf272cd0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":415,
                      "y":60},
                    "size":{
                      "width":122,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/单据打印/u121.png"}}]},
{
          "id":"f1014799c4b1415b9c6b42d6c3544b43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":615,
              "y":1150},
            "size":{
              "width":40,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0799673d12c24c4090b6fd8dfdb2004a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":615,
                  "y":1150},
                "size":{
                  "width":40,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e250cf42e1294a3dae38a29ff47747c9":{
      "scriptId":"u0"},
    "7ace0f1bc534497eb060f59aaec1d73e":{
      "scriptId":"u1"},
    "b6c594ded71f4f4091e1157bc5c8c2da":{
      "scriptId":"u2"},
    "348c06a0ff7d40e1834cf68bced1b86f":{
      "scriptId":"u3"},
    "4f970d49116448aa8eb459db3b79b098":{
      "scriptId":"u4"},
    "77575d9cffa54e30841bb5ca5013d178":{
      "scriptId":"u5"},
    "f7e8f03d1ebd48e081da789ed5bad6f0":{
      "scriptId":"u6"},
    "3288ea8397044c9e839ee1bde8bd68fb":{
      "scriptId":"u7"},
    "d9bf15559bc14b438724459bbb92623f":{
      "scriptId":"u8"},
    "235cd3fcc1324702983714594a80424a":{
      "scriptId":"u9"},
    "ae99223fd0bc4e6e852dcbde69f2ae0a":{
      "scriptId":"u10"},
    "dda413be06fb4ade8b1abe0638bdb945":{
      "scriptId":"u11"},
    "75df2edd100341ac9920cf3d58210a1b":{
      "scriptId":"u12"},
    "7ceff9aae4e24402a3f5ca83d0d1d990":{
      "scriptId":"u13"},
    "f17581f714424ceb8117c8d3ff030127":{
      "scriptId":"u14"},
    "f4a736ffc9364d4882da53c851d35651":{
      "scriptId":"u15"},
    "41503ee044b24b188c2e7d1a5c41eb2b":{
      "scriptId":"u16"},
    "f14aed93d7f54933a83ccbc61c62022d":{
      "scriptId":"u17"},
    "b542206497b8473ca8e2d2adcff4f749":{
      "scriptId":"u18"},
    "3b67697d992b4c5dae32f745c4d1c2ae":{
      "scriptId":"u19"},
    "535ad160f7d1463d820019ad81171f0a":{
      "scriptId":"u20"},
    "740da0f2686d4233890ae8a5c6220aae":{
      "scriptId":"u21"},
    "2259e958117c42cd8b5cc3a83455fbc4":{
      "scriptId":"u22"},
    "603354b0b7764699aae5609e9a1603fb":{
      "scriptId":"u23"},
    "e7cde3668f4a45b1ad4aa755d10673e0":{
      "scriptId":"u24"},
    "b779424371ea47e98078c5c1705f4b8b":{
      "scriptId":"u25"},
    "a935db9b3361454ebc0c1c4997950ef5":{
      "scriptId":"u26"},
    "1525be1a80354cabae1db94a4a0b2657":{
      "scriptId":"u27"},
    "599bc0aa899a4484bde196ec75bd80c6":{
      "scriptId":"u28"},
    "1420c6d08db04953b87b0aa78c4e8a9e":{
      "scriptId":"u29"},
    "9e180ea60105454d8ee13a18bfde7c5d":{
      "scriptId":"u30"},
    "d0037d36beb24fc387416ddf07aa563d":{
      "scriptId":"u31"},
    "d4fbbe2c26074c4daa473f966702e884":{
      "scriptId":"u32"},
    "11f50c8ec2fa4e02b67ccb01e053a565":{
      "scriptId":"u33"},
    "cd24f92ba37d4a9e8f1de96ab20e8600":{
      "scriptId":"u34"},
    "387064ee99d04099ab1b738eef0df322":{
      "scriptId":"u35"},
    "01a10288f2cc4160ad18e08b09a61bd5":{
      "scriptId":"u36"},
    "1cb848eda7c74385bee5bbd20b4acd84":{
      "scriptId":"u37"},
    "3a17891569da4eb6be9ff07e5f78ca8e":{
      "scriptId":"u38"},
    "b16a04eb70984f11b196c9644c6b8443":{
      "scriptId":"u39"},
    "dbd25a2599064f5da50cf3f87bcbcf11":{
      "scriptId":"u40"},
    "ab39ced7b3ab462ea5786186f8b50a16":{
      "scriptId":"u41"},
    "f14e50d4e98e40e0b4887a57b402cbd3":{
      "scriptId":"u42"},
    "d063ca963d5f4c6385fd02c06fc444b7":{
      "scriptId":"u43"},
    "53341c08273640c3b9ce6b7915c50ef2":{
      "scriptId":"u44"},
    "57efd82fd5924adfb9a124fbd809e877":{
      "scriptId":"u45"},
    "c2d7400e7ce7497b82e54ab80a3bd3bc":{
      "scriptId":"u46"},
    "ed9946e5b9c2418ab6bf84a261896fe7":{
      "scriptId":"u47"},
    "783abe926deb45b9b7ff8066eb9346fa":{
      "scriptId":"u48"},
    "ec95193f90e84420b3eddf64340d9ea8":{
      "scriptId":"u49"},
    "7cc6c765a6534904b230a1d585b7a658":{
      "scriptId":"u50"},
    "b8a0b211d0f041efafc88da696556b96":{
      "scriptId":"u51"},
    "0604865687f54954a5a9951b57f8a1ad":{
      "scriptId":"u52"},
    "c8a5af4fd3164c5692c225917a7b15a0":{
      "scriptId":"u53"},
    "25575000f9a54cde9c6ea9b27d4e6c2b":{
      "scriptId":"u54"},
    "2af64839fe254fb3a85a739073184af4":{
      "scriptId":"u55"},
    "021262e6df664d218ef50b8b9affafa2":{
      "scriptId":"u56"},
    "3509ea5528e0438aba65b5c50cef68ca":{
      "scriptId":"u57"},
    "2b104764d3224fd28b88c4e8a82ac155":{
      "scriptId":"u58"},
    "0299a6911e6344e882465cb29eb526aa":{
      "scriptId":"u59"},
    "567b08a9e33b4ece87de8d42f54c2a1c":{
      "scriptId":"u60"},
    "9d3b1824e7974023ac1089bccc122428":{
      "scriptId":"u61"},
    "e68cc2b3f2964222ab4072b3531d1faa":{
      "scriptId":"u62"},
    "a15faf1c466b4d98a8bc906ba58d4e28":{
      "scriptId":"u63"},
    "5b887a95f5b744e1a7b2534e23ee36af":{
      "scriptId":"u64"},
    "77a67e38fa5a4eea836a6c7b44506115":{
      "scriptId":"u65"},
    "3043a9fb1ad64767a2e5d4abd12559f9":{
      "scriptId":"u66"},
    "d87cf082824a4a4d87c2c4fb1626e182":{
      "scriptId":"u67"},
    "e7c6424bef3d43bca6593f179c5264d6":{
      "scriptId":"u68"},
    "74ad864786974113888e9216a7eceefe":{
      "scriptId":"u69"},
    "78df47a88ddd444abe28c53c3fd26880":{
      "scriptId":"u70"},
    "b07aca2f05cd41949bf7757e94b7212d":{
      "scriptId":"u71"},
    "e6813d8a5aea4ac3abc222e472fd587a":{
      "scriptId":"u72"},
    "eb17a42b3b664cbb88e11719614ce52e":{
      "scriptId":"u73"},
    "6a5cd628f19c4831b08b2dcc0cba71d2":{
      "scriptId":"u74"},
    "c03452ff3edd4ecebec1f5170776bbb8":{
      "scriptId":"u75"},
    "54475987bcf54fa6b1440195885fe60b":{
      "scriptId":"u76"},
    "d9b4c3a02eb644118994320e8ee7d783":{
      "scriptId":"u77"},
    "ec10b26df1c449d3b2144de3ad659918":{
      "scriptId":"u78"},
    "16c211edd9514aa2b2b82542dcb7ee3a":{
      "scriptId":"u79"},
    "f143fb5e7c9043fab4ea4fa18b34a47e":{
      "scriptId":"u80"},
    "987cf6b9649149f09488a41106c42adb":{
      "scriptId":"u81"},
    "95564d052e494d92832369396f6ee84c":{
      "scriptId":"u82"},
    "e647a570d65b41a8b89973fa2c0c6b5f":{
      "scriptId":"u83"},
    "71636e6f87c047f4ad90e3d141c820d5":{
      "scriptId":"u84"},
    "fd3fbf5203d142fda4ebb5ea76f3dd36":{
      "scriptId":"u85"},
    "2bd3ddb2e5d84b018252f7b23cbe625d":{
      "scriptId":"u86"},
    "66f21eca6386435688fba5d144411165":{
      "scriptId":"u87"},
    "a58f9d8f34a14b35ae8ec3651776e0f6":{
      "scriptId":"u88"},
    "df13e2f6d7544e19b5019545f9bb2312":{
      "scriptId":"u89"},
    "94ecab6e8eaf4319b2226261f762aa65":{
      "scriptId":"u90"},
    "c35ccfb1bb044fe9aea26a4dfda40883":{
      "scriptId":"u91"},
    "fe50b657d3334d10a8831b74c0e56488":{
      "scriptId":"u92"},
    "04858c2ceecb4cd7ae9f1f163ff164f0":{
      "scriptId":"u93"},
    "ff08888455584b9ca319d8fcf2818efb":{
      "scriptId":"u94"},
    "52fe925ea0c84c29859a2a0a5348720d":{
      "scriptId":"u95"},
    "41b3ff8d95604163ae9edeff508a9e88":{
      "scriptId":"u96"},
    "b480297d35394d6e97e4e8b122f56c93":{
      "scriptId":"u97"},
    "1c5e99b6e49942ac8c8ddccd4eac627b":{
      "scriptId":"u98"},
    "3821773a745b4d57b572e748a2fae75b":{
      "scriptId":"u99"},
    "e33af7737f864364b52dc821ce875b9a":{
      "scriptId":"u100"},
    "2710b193b31a4c77a1b6d4985fe4f468":{
      "scriptId":"u101"},
    "9987ac8509794a97a4d1e835d054cf1b":{
      "scriptId":"u102"},
    "a7d09845e3d543f8a9190c92f90c9cce":{
      "scriptId":"u103"},
    "35bb378fca194e92a145b6bf45942e07":{
      "scriptId":"u104"},
    "439507ec2e7f47eab1dbdf9edd97bea3":{
      "scriptId":"u105"},
    "9a841a5db27b42d28b4eeb373f5bc2e1":{
      "scriptId":"u106"},
    "1f0a3f5b1ea048128025396d141e34ab":{
      "scriptId":"u107"},
    "24beed00a0cf4e80b0856e7b3dd2e565":{
      "scriptId":"u108"},
    "a5751d0e9d5e4f31a372c461e0b7e504":{
      "scriptId":"u109"},
    "5e2bb3cebafb4f2daf821cf87bad378e":{
      "scriptId":"u110"},
    "453ec0c970ea4d27925fcd7caae1374a":{
      "scriptId":"u111"},
    "ea15a1ccee8e4758998df507653a4ed7":{
      "scriptId":"u112"},
    "3876daca082044148c4c945a768a4923":{
      "scriptId":"u113"},
    "698b456d0b484ad5a0544721fb26ad37":{
      "scriptId":"u114"},
    "080b4f2db92e42ae8c49824c0a97d2a2":{
      "scriptId":"u115"},
    "496eec27ca1e41cfa7d7a8b769486958":{
      "scriptId":"u116"},
    "26129e5bec7e45ac930a07b13201338a":{
      "scriptId":"u117"},
    "b27f01098c9e4f219acc059e5faa1097":{
      "scriptId":"u118"},
    "726dab6e797e406287c4d3f61b9c7d50":{
      "scriptId":"u119"},
    "77ef56b616a64489aa4a1a30bf41a224":{
      "scriptId":"u120"},
    "188606b216744f33ad703471b92dd6f1":{
      "scriptId":"u121"},
    "7d3397a82c534f19a43647eedf272cd0":{
      "scriptId":"u122"},
    "f1014799c4b1415b9c6b42d6c3544b43":{
      "scriptId":"u123"},
    "0799673d12c24c4090b6fd8dfdb2004a":{
      "scriptId":"u124"}}});