$axure.loadCurrentPage({
  "url":"flow.html",
  "generationDate":new Date(1450315457993.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"26aa659418cd4cc79d300e0b19c411f0",
    "type":"Axure:Page",
    "name":"Flow",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6aa4a79eacd242998a9a3fdd822c36b7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":342,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec74815bd18b40a0900bb1fbf2dd3857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":342,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"6399dee1208542d286446746dd6e1a9a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":484,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b40d0e41594428ea7cbfe143f2d59a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":484,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"905c60a353cb49bdbc826704c6e7d70d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":625,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c47060a1ca43bda3f3470e6f155ba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":625,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"745b30f069234e8b95754bd4642dd6f7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":766,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b169a6bf4548a1a80204ed2f77df31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":766,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"1dbd4d8c35354f9a8adc0e5d94e99dd0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":913,
              "y":280},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69246b1b1c0485ca17c644f2809f0e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":913,
                  "y":280},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"8e63b523f4f4453590336be88b3359b1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1060,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ebef08b4ae4ebfa08f29fc8c5e4427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1060,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"e8465f49fcb645d4bbbee26275d31ca9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1210,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd069404f744016968085fae1b6b95a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1210,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"41783f6893324ea482a3d9980fe00f72",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":60,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdce71901a3a43559d46d52ac7aa735e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":60,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"f095b489bf784486a21c558c5e400426",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":201,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0087bd9e50b4d01ba13909222053840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":201,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"2f978c9f1ca248638a716883533e1727",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":913,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf1f6e31b0e4bcfafd115c344ee7b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":913,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"9b268ea29f8d4f00934ecd241805db04",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":766,
              "y":280},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d1526fc89f3447aadb32c79dae2eb8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":766,
                  "y":280},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"34093014ba254599b4782bd69836b778",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7047df38be2c4dbdbdac86cfc851c3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"f371561308d24a64bf140b8e3e6088e8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe051203f00442ecbe7f67157303ca22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":301,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"8afbc1e6ae99408db74c0efe8409f88a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b247223ce3a541598a65cadbec2318df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"132ca134ead04a08aec7d14102246975",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f077e807975498da792e55209708476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"c0daa935c7834354a6e72ad5b05236da",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":725,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6538d9ec8ee34ce1bc500b70845d9273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":725,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"2389d5a3d374480f97d8d79e9277b73b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":217},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c89b5e5a904e099401a56938a8a415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":217},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"a8d2bc04ae1d48a2b1be68e404d3f8a4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":866,
              "y":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411b197a46764020acf5d4761b96a06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":866,
                  "y":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"d6f264329c894c349481d6d6cfe071ba",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":157},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5b62fcb96e4bce941b648c7a22b7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1060,
                  "y":157},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow/u36.png"}},
{
          "id":"18e26a99df5947c98796a0941ae16152",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":866,
              "y":187},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48b553ce38048cdb174969dbd1ae8f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":866,
                  "y":187},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}]},
{
          "id":"b6068e7e1b6c4f98a638dd36744a2fd1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":430},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824e2e76ecd9491bb77e174499ca0205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":430},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}]},
{
          "id":"539b7612295e48e78d10cebd2d5e5797",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1210,
              "y":510},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dedbf6ea9114ceab28f397b81349589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1210,
                  "y":510},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/structure/u120.png"}},
{
          "id":"6fb4c1e1be974b3ba43763568d47e1eb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1260,
              "y":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ddddb9449e2496990a6044df634d7a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1260,
                  "y":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0437e618e9de4c13b8002130d411be06",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1013,
              "y":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ba012a5f454b8f8c5463e0af9e58b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1013,
                  "y":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600}},
              "adaptiveStyles":{
}}]},
{
          "id":"a8dfdd95d3464ae981fa7b46535655e3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":963,
              "y":340},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff2403c88164761977241c4114620a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":963,
                  "y":340},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"8c09c9900f1c49e8b59109bc200ac3f3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1013,
              "y":430},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd12693f09a49bf82b100e3fb7ad172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1013,
                  "y":430},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"aa7a1f3b2daf471aa97aea2adc228ec7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":430},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8365513edb6042cbad9cc549610b007c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1160,
                  "y":430},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"957b7eee90594478b67e20d3f187d742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":60,
              "y":138},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1681e7e37f864aad9e5caf20d3364e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":60,
                  "y":138},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"808f9258e28945dc84667236bd2c4424",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":204,
              "y":138},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78350f875c1d46a58eb92479372169eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":204,
                  "y":138},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1936779a64824584bb514ed9a5de5b84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":344,
              "y":138},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b027c37ff23645ee8445c96ece292be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":344,
                  "y":138},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40565644fb5649d8900d16d392900f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":486,
              "y":138},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e71fa1b128a641d5915d9000f7c585dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":486,
                  "y":138},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db5d91bed8894113b347fd903db91ae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":628,
              "y":138},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b37bb3c34c994bb488d5b5627d4d7527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":628,
                  "y":138},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a39a7a1fa1a74f528fb4bdb75c22c86d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":767,
              "y":138},
            "size":{
              "width":72,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9235019e5baf44f19f4db214b45f2b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":767,
                  "y":138},
                "size":{
                  "width":72,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adde358862a14e54902ad92a3cc7f3f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":766,
              "y":261},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"639376ce5895441d88e32a6a3ced7d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":766,
                  "y":261},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e2f2379d284ac2ae63da6f729ebaa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":261},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e58fee15024106bb4b395302c64fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":261},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efc56c83b3a94944a18ec7766e4646fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":913,
              "y":381},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82155391d285417fa1892defca130e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":913,
                  "y":381},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a6eaea0703d44e097fd098b38d5fd55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1060,
              "y":381},
            "size":{
              "width":59,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93edb735f1af4bb485586f1e4fb5c6b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1060,
                  "y":381},
                "size":{
                  "width":59,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a2bd8eccb349c98296e5eea03b913a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1210,
              "y":381},
            "size":{
              "width":72,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a445a66c385044be9edd5e36f75cddb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1210,
                  "y":381},
                "size":{
                  "width":72,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2969374236e64c31bef406f1ce883269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1210,
              "y":491},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f287dc64ef0422c86c65f61c8467e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1210,
                  "y":491},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9225fa3deaae411e81f322de8bb4f94a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":700,
              "y":420},
            "size":{
              "width":190,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c12271aac34b8b91fbb3361c760f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":700,
                  "y":420},
                "size":{
                  "width":190,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow/u78.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6aa4a79eacd242998a9a3fdd822c36b7":{
      "scriptId":"u0"},
    "ec74815bd18b40a0900bb1fbf2dd3857":{
      "scriptId":"u1"},
    "6399dee1208542d286446746dd6e1a9a":{
      "scriptId":"u2"},
    "9b40d0e41594428ea7cbfe143f2d59a6":{
      "scriptId":"u3"},
    "905c60a353cb49bdbc826704c6e7d70d":{
      "scriptId":"u4"},
    "67c47060a1ca43bda3f3470e6f155ba4":{
      "scriptId":"u5"},
    "745b30f069234e8b95754bd4642dd6f7":{
      "scriptId":"u6"},
    "86b169a6bf4548a1a80204ed2f77df31":{
      "scriptId":"u7"},
    "1dbd4d8c35354f9a8adc0e5d94e99dd0":{
      "scriptId":"u8"},
    "b69246b1b1c0485ca17c644f2809f0e3":{
      "scriptId":"u9"},
    "8e63b523f4f4453590336be88b3359b1":{
      "scriptId":"u10"},
    "20ebef08b4ae4ebfa08f29fc8c5e4427":{
      "scriptId":"u11"},
    "e8465f49fcb645d4bbbee26275d31ca9":{
      "scriptId":"u12"},
    "dbd069404f744016968085fae1b6b95a":{
      "scriptId":"u13"},
    "41783f6893324ea482a3d9980fe00f72":{
      "scriptId":"u14"},
    "bdce71901a3a43559d46d52ac7aa735e":{
      "scriptId":"u15"},
    "f095b489bf784486a21c558c5e400426":{
      "scriptId":"u16"},
    "e0087bd9e50b4d01ba13909222053840":{
      "scriptId":"u17"},
    "2f978c9f1ca248638a716883533e1727":{
      "scriptId":"u18"},
    "dbf1f6e31b0e4bcfafd115c344ee7b23":{
      "scriptId":"u19"},
    "9b268ea29f8d4f00934ecd241805db04":{
      "scriptId":"u20"},
    "7d1526fc89f3447aadb32c79dae2eb8c":{
      "scriptId":"u21"},
    "34093014ba254599b4782bd69836b778":{
      "scriptId":"u22"},
    "7047df38be2c4dbdbdac86cfc851c3a9":{
      "scriptId":"u23"},
    "f371561308d24a64bf140b8e3e6088e8":{
      "scriptId":"u24"},
    "fe051203f00442ecbe7f67157303ca22":{
      "scriptId":"u25"},
    "8afbc1e6ae99408db74c0efe8409f88a":{
      "scriptId":"u26"},
    "b247223ce3a541598a65cadbec2318df":{
      "scriptId":"u27"},
    "132ca134ead04a08aec7d14102246975":{
      "scriptId":"u28"},
    "2f077e807975498da792e55209708476":{
      "scriptId":"u29"},
    "c0daa935c7834354a6e72ad5b05236da":{
      "scriptId":"u30"},
    "6538d9ec8ee34ce1bc500b70845d9273":{
      "scriptId":"u31"},
    "2389d5a3d374480f97d8d79e9277b73b":{
      "scriptId":"u32"},
    "94c89b5e5a904e099401a56938a8a415":{
      "scriptId":"u33"},
    "a8d2bc04ae1d48a2b1be68e404d3f8a4":{
      "scriptId":"u34"},
    "411b197a46764020acf5d4761b96a06f":{
      "scriptId":"u35"},
    "d6f264329c894c349481d6d6cfe071ba":{
      "scriptId":"u36"},
    "4f5b62fcb96e4bce941b648c7a22b7b5":{
      "scriptId":"u37"},
    "18e26a99df5947c98796a0941ae16152":{
      "scriptId":"u38"},
    "c48b553ce38048cdb174969dbd1ae8f7":{
      "scriptId":"u39"},
    "b6068e7e1b6c4f98a638dd36744a2fd1":{
      "scriptId":"u40"},
    "824e2e76ecd9491bb77e174499ca0205":{
      "scriptId":"u41"},
    "539b7612295e48e78d10cebd2d5e5797":{
      "scriptId":"u42"},
    "2dedbf6ea9114ceab28f397b81349589":{
      "scriptId":"u43"},
    "6fb4c1e1be974b3ba43763568d47e1eb":{
      "scriptId":"u44"},
    "9ddddb9449e2496990a6044df634d7a9":{
      "scriptId":"u45"},
    "0437e618e9de4c13b8002130d411be06":{
      "scriptId":"u46"},
    "27ba012a5f454b8f8c5463e0af9e58b9":{
      "scriptId":"u47"},
    "a8dfdd95d3464ae981fa7b46535655e3":{
      "scriptId":"u48"},
    "dff2403c88164761977241c4114620a3":{
      "scriptId":"u49"},
    "8c09c9900f1c49e8b59109bc200ac3f3":{
      "scriptId":"u50"},
    "bfd12693f09a49bf82b100e3fb7ad172":{
      "scriptId":"u51"},
    "aa7a1f3b2daf471aa97aea2adc228ec7":{
      "scriptId":"u52"},
    "8365513edb6042cbad9cc549610b007c":{
      "scriptId":"u53"},
    "957b7eee90594478b67e20d3f187d742":{
      "scriptId":"u54"},
    "1681e7e37f864aad9e5caf20d3364e38":{
      "scriptId":"u55"},
    "808f9258e28945dc84667236bd2c4424":{
      "scriptId":"u56"},
    "78350f875c1d46a58eb92479372169eb":{
      "scriptId":"u57"},
    "1936779a64824584bb514ed9a5de5b84":{
      "scriptId":"u58"},
    "b027c37ff23645ee8445c96ece292be4":{
      "scriptId":"u59"},
    "40565644fb5649d8900d16d392900f1f":{
      "scriptId":"u60"},
    "e71fa1b128a641d5915d9000f7c585dc":{
      "scriptId":"u61"},
    "db5d91bed8894113b347fd903db91ae0":{
      "scriptId":"u62"},
    "b37bb3c34c994bb488d5b5627d4d7527":{
      "scriptId":"u63"},
    "a39a7a1fa1a74f528fb4bdb75c22c86d":{
      "scriptId":"u64"},
    "9235019e5baf44f19f4db214b45f2b14":{
      "scriptId":"u65"},
    "adde358862a14e54902ad92a3cc7f3f2":{
      "scriptId":"u66"},
    "639376ce5895441d88e32a6a3ced7d55":{
      "scriptId":"u67"},
    "20e2f2379d284ac2ae63da6f729ebaa9":{
      "scriptId":"u68"},
    "e0e58fee15024106bb4b395302c64fa8":{
      "scriptId":"u69"},
    "efc56c83b3a94944a18ec7766e4646fc":{
      "scriptId":"u70"},
    "82155391d285417fa1892defca130e4d":{
      "scriptId":"u71"},
    "7a6eaea0703d44e097fd098b38d5fd55":{
      "scriptId":"u72"},
    "93edb735f1af4bb485586f1e4fb5c6b4":{
      "scriptId":"u73"},
    "31a2bd8eccb349c98296e5eea03b913a":{
      "scriptId":"u74"},
    "a445a66c385044be9edd5e36f75cddb6":{
      "scriptId":"u75"},
    "2969374236e64c31bef406f1ce883269":{
      "scriptId":"u76"},
    "5f287dc64ef0422c86c65f61c8467e51":{
      "scriptId":"u77"},
    "9225fa3deaae411e81f322de8bb4f94a":{
      "scriptId":"u78"},
    "66c12271aac34b8b91fbb3361c760f33":{
      "scriptId":"u79"}}});