$axure.loadCurrentPage({
  "url":"查看过往病历.html",
  "generationDate":new Date(1450315459962.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9e1ec002ea4b488b928881bb045a412d",
    "type":"Axure:Page",
    "name":"查看过往病历",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee8bc7cf7e19492cb37a4931b5a98d16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":1000,
              "height":790},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a3441eb81042afad5170f0902bd08c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":60},
                "size":{
                  "width":1000,
                  "height":790},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看过往病历/u0.png"}},
{
          "id":"f817b13c392840cf9bd8842006275a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Verdana Normal', 'Verdana'",
            "fontSize":"48px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":996,
              "y":60},
            "size":{
              "width":34,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556e4f4ded9446458720d0b8e1256562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Verdana Normal', 'Verdana'",
                "fontSize":"48px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":996,
                  "y":60},
                "size":{
                  "width":34,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d29e34777894f7ebd6cbeb5e716f4a3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":120},
            "size":{
              "width":980,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者内页/u4_line.png"}},
{
          "id":"4cf978f7362d4a4193e5bb2847f5a7be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":96},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce9e7925f494714993f8adf08839009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":96},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10f8f5f5389246afba84371b654341a4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":120},
            "size":{
              "width":90,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者内页/u7_line.png"}},
{
          "id":"4fded6f635d448ba89352406fded1006",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":88,
              "y":149},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7013b92b0afa4a549effe6b9ebe9c44f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":149},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f42607f9574b484880010f820a6022c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":134,
              "y":146},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"74848af5d2c6449094ad32e756f436bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":283,
              "y":148},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1e92e1a203c425a91a21aa095d3f88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":148},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bf6239e15bb4a71a8261531aeaa1300",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":148},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"cbfb7ab538f14f5fbf2075b534753441",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":479,
              "y":150},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703ab88feec242f4a79e9b699643ce07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":150},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0a412c166bc48f991145306328e4c3f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":525,
              "y":146},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e7f51421b3bf41298771d84c5dfe7ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":203},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0034ebad5744e51bfe4aaa091b680a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":203},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b427862cfd2f4173a98599a9f05f4471",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":134,
              "y":199},
            "size":{
              "width":220,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f11cc4c55e494440b24fec5ac8927893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":451,
              "y":203},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69437945de11487792efd3f1cd78f4d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":451,
                  "y":203},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4df10b7bbe24c509dddfcd6d066d819",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":525,
              "y":199},
            "size":{
              "width":220,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"eda0b5c670d6440b8ba1ae1071e372dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":300},
            "size":{
              "width":980,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者内页/u4_line.png"}},
{
          "id":"be1b491354e94151ac6be142d5eaa5f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":276},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5550688a44bd44288bb650f358652ea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":276},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a7ee28d5531424d941e098217d39c03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":300},
            "size":{
              "width":90,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者内页/u7_line.png"}},
{
          "id":"67867eb9e70549938e00aa2c2a8bdb36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":696,
              "y":148},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56f998652df1439c91249433bee9d51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":696,
                  "y":148},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7694cc98aeec4d42a19ea9ca5430d315",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":770,
              "y":144},
            "size":{
              "width":220,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45f85b09f8714d1da3ed83f53d5e5f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":338},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d604018c9d224d758dbc31d6cf67391f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":338},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e56acc1bdd0c4965844e40e647bf754e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":88,
              "y":389},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ec87587261458c93be32cf627e336c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":389},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"167c57e405d24b8687baed03b8df6855",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":134,
              "y":385},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f18a16c7804744d78ca63d3f4285da1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":283,
              "y":389},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff33a165ef4d44ceb3b58a91ef4e4548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":389},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69c293611fcc4c769dfbeb70c0039b21",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":385},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2bad177c39246da8e6387775f6ec66c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":479,
              "y":388},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad743998f2bb4c47a8e1311c7e477769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":388},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"135d779a885d43d282ce7b16ea2d60f8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":525,
              "y":384},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6b5deb0a9e6e4e4bbd542c11aca25a6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":74,
              "y":440},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ee1384527e4cfa8e955c7eb6178db2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":440},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a942107e0bb457b908257a621594fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":480},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3245724a07874e808dc0fb0e2c92c06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":480},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4919e377fffd4b5bb3cd6980ab44698f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":438},
            "size":{
              "width":716,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a9222676126411e8379e5a34cdfaf24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":88,
              "y":522},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a144108a05d415bbf50abd5748f458b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":522},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801b0de1be2d4c449d560b3164d7825a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":520},
            "size":{
              "width":716,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dce825e5935f4360ba59f7615f7454a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":567},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468e46b408494de6aceadf4b2eb7490a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":567},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cf0410c59894659bd37297994c5b2e0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":565},
            "size":{
              "width":716,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1451df5fb97d40f4814f92a2d7179b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":88,
              "y":612},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b6b05484c1454c8943bb5f54ec64e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":612},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9519b1277e494b4cbee0bcefbfe76e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":650},
            "size":{
              "width":209,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a204ec88b6fd4349840c7e690a833f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":650},
                "size":{
                  "width":209,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d20a86f9b28249a2ac8c1218ed247372",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":933,
              "y":277},
            "size":{
              "width":97,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ceb8a1743c4b7b92286708bb35510d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":933,
                  "y":277},
                "size":{
                  "width":97,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者内页",
                      "target":{
                        "targetType":"page",
                        "url":"患者内页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cf0020423f1473c9ca5b04b62d22284",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":478},
            "size":{
              "width":716,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"25a915e48c074bfeb9fd9820dedd43f1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":336},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0b83f70e3ce747608537d5fdd11fab6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":614},
            "size":{
              "width":27,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"926b4e1c8aa7403e9354bfa3bc28e3ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":614},
                "size":{
                  "width":27,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38ce51d4149d4e1abc88649e8104cab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":690},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de6c66adeb24a5880559603a22f1340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":690},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d953123cb3c4321947dde8e599f7042",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":131,
              "y":690},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5deeec1be5d4e54a81d99851d801941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":131,
                  "y":690},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642cc46cbd454d8e992f3edf2c16621b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1080,
              "y":685},
            "size":{
              "width":220,
              "height":55},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e59ad600cc424291a588c1e1051dd65f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1080,
                  "y":685},
                "size":{
                  "width":220,
                  "height":55},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看过往病历/u66.png"}},
{
          "id":"26f95961a5584eaab3294fca8e43ace7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":60,
              "y":732},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b38b0cce7c4035b465f2795176aa2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":732},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ee4e2af0a55440a996387277d36e39d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":131,
              "y":732},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc731f4dbb94ef4a7d02b775a331213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":131,
                  "y":732},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a0014de07e4a32927f2fd0d85d9607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1080,
              "y":270},
            "size":{
              "width":220,
              "height":34},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd1d01afdea4a61abc0f90462d2d5e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1080,
                  "y":270},
                "size":{
                  "width":220,
                  "height":34},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看过往病历/u72.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee8bc7cf7e19492cb37a4931b5a98d16":{
      "scriptId":"u0"},
    "f4a3441eb81042afad5170f0902bd08c":{
      "scriptId":"u1"},
    "f817b13c392840cf9bd8842006275a62":{
      "scriptId":"u2"},
    "556e4f4ded9446458720d0b8e1256562":{
      "scriptId":"u3"},
    "6d29e34777894f7ebd6cbeb5e716f4a3":{
      "scriptId":"u4"},
    "4cf978f7362d4a4193e5bb2847f5a7be":{
      "scriptId":"u5"},
    "5ce9e7925f494714993f8adf08839009":{
      "scriptId":"u6"},
    "10f8f5f5389246afba84371b654341a4":{
      "scriptId":"u7"},
    "4fded6f635d448ba89352406fded1006":{
      "scriptId":"u8"},
    "7013b92b0afa4a549effe6b9ebe9c44f":{
      "scriptId":"u9"},
    "f42607f9574b484880010f820a6022c1":{
      "scriptId":"u10"},
    "74848af5d2c6449094ad32e756f436bf":{
      "scriptId":"u11"},
    "b1e92e1a203c425a91a21aa095d3f88f":{
      "scriptId":"u12"},
    "3bf6239e15bb4a71a8261531aeaa1300":{
      "scriptId":"u13"},
    "cbfb7ab538f14f5fbf2075b534753441":{
      "scriptId":"u14"},
    "703ab88feec242f4a79e9b699643ce07":{
      "scriptId":"u15"},
    "f0a412c166bc48f991145306328e4c3f":{
      "scriptId":"u16"},
    "e7f51421b3bf41298771d84c5dfe7ea1":{
      "scriptId":"u17"},
    "b0034ebad5744e51bfe4aaa091b680a0":{
      "scriptId":"u18"},
    "b427862cfd2f4173a98599a9f05f4471":{
      "scriptId":"u19"},
    "f11cc4c55e494440b24fec5ac8927893":{
      "scriptId":"u20"},
    "69437945de11487792efd3f1cd78f4d1":{
      "scriptId":"u21"},
    "d4df10b7bbe24c509dddfcd6d066d819":{
      "scriptId":"u22"},
    "eda0b5c670d6440b8ba1ae1071e372dd":{
      "scriptId":"u23"},
    "be1b491354e94151ac6be142d5eaa5f9":{
      "scriptId":"u24"},
    "5550688a44bd44288bb650f358652ea5":{
      "scriptId":"u25"},
    "4a7ee28d5531424d941e098217d39c03":{
      "scriptId":"u26"},
    "67867eb9e70549938e00aa2c2a8bdb36":{
      "scriptId":"u27"},
    "56f998652df1439c91249433bee9d51e":{
      "scriptId":"u28"},
    "7694cc98aeec4d42a19ea9ca5430d315":{
      "scriptId":"u29"},
    "45f85b09f8714d1da3ed83f53d5e5f78":{
      "scriptId":"u30"},
    "d604018c9d224d758dbc31d6cf67391f":{
      "scriptId":"u31"},
    "e56acc1bdd0c4965844e40e647bf754e":{
      "scriptId":"u32"},
    "47ec87587261458c93be32cf627e336c":{
      "scriptId":"u33"},
    "167c57e405d24b8687baed03b8df6855":{
      "scriptId":"u34"},
    "f18a16c7804744d78ca63d3f4285da1a":{
      "scriptId":"u35"},
    "ff33a165ef4d44ceb3b58a91ef4e4548":{
      "scriptId":"u36"},
    "69c293611fcc4c769dfbeb70c0039b21":{
      "scriptId":"u37"},
    "f2bad177c39246da8e6387775f6ec66c":{
      "scriptId":"u38"},
    "ad743998f2bb4c47a8e1311c7e477769":{
      "scriptId":"u39"},
    "135d779a885d43d282ce7b16ea2d60f8":{
      "scriptId":"u40"},
    "6b5deb0a9e6e4e4bbd542c11aca25a6a":{
      "scriptId":"u41"},
    "f9ee1384527e4cfa8e955c7eb6178db2":{
      "scriptId":"u42"},
    "4a942107e0bb457b908257a621594fd1":{
      "scriptId":"u43"},
    "3245724a07874e808dc0fb0e2c92c06f":{
      "scriptId":"u44"},
    "4919e377fffd4b5bb3cd6980ab44698f":{
      "scriptId":"u45"},
    "9a9222676126411e8379e5a34cdfaf24":{
      "scriptId":"u46"},
    "1a144108a05d415bbf50abd5748f458b":{
      "scriptId":"u47"},
    "801b0de1be2d4c449d560b3164d7825a":{
      "scriptId":"u48"},
    "dce825e5935f4360ba59f7615f7454a8":{
      "scriptId":"u49"},
    "468e46b408494de6aceadf4b2eb7490a":{
      "scriptId":"u50"},
    "2cf0410c59894659bd37297994c5b2e0":{
      "scriptId":"u51"},
    "1451df5fb97d40f4814f92a2d7179b2c":{
      "scriptId":"u52"},
    "41b6b05484c1454c8943bb5f54ec64e4":{
      "scriptId":"u53"},
    "9519b1277e494b4cbee0bcefbfe76e40":{
      "scriptId":"u54"},
    "a204ec88b6fd4349840c7e690a833f31":{
      "scriptId":"u55"},
    "d20a86f9b28249a2ac8c1218ed247372":{
      "scriptId":"u56"},
    "20ceb8a1743c4b7b92286708bb35510d":{
      "scriptId":"u57"},
    "9cf0020423f1473c9ca5b04b62d22284":{
      "scriptId":"u58"},
    "25a915e48c074bfeb9fd9820dedd43f1":{
      "scriptId":"u59"},
    "0b83f70e3ce747608537d5fdd11fab6d":{
      "scriptId":"u60"},
    "926b4e1c8aa7403e9354bfa3bc28e3ab":{
      "scriptId":"u61"},
    "38ce51d4149d4e1abc88649e8104cab4":{
      "scriptId":"u62"},
    "0de6c66adeb24a5880559603a22f1340":{
      "scriptId":"u63"},
    "6d953123cb3c4321947dde8e599f7042":{
      "scriptId":"u64"},
    "a5deeec1be5d4e54a81d99851d801941":{
      "scriptId":"u65"},
    "642cc46cbd454d8e992f3edf2c16621b":{
      "scriptId":"u66"},
    "e59ad600cc424291a588c1e1051dd65f":{
      "scriptId":"u67"},
    "26f95961a5584eaab3294fca8e43ace7":{
      "scriptId":"u68"},
    "86b38b0cce7c4035b465f2795176aa2c":{
      "scriptId":"u69"},
    "7ee4e2af0a55440a996387277d36e39d":{
      "scriptId":"u70"},
    "acc731f4dbb94ef4a7d02b775a331213":{
      "scriptId":"u71"},
    "26a0014de07e4a32927f2fd0d85d9607":{
      "scriptId":"u72"},
    "cfd1d01afdea4a61abc0f90462d2d5e3":{
      "scriptId":"u73"}}});