$axure.loadCurrentPage({
  "url":"患者队列.html",
  "generationDate":new Date(1450315459446.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8bbc579239540ed8b41bd8df714e69b",
    "type":"Axure:Page",
    "name":"患者队列",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83e95a882326406dbeabc3dc65768974",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":1000,
              "height":720},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370ce8ab2b05414cb403d6c5ea11c43c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":60},
                "size":{
                  "width":1000,
                  "height":720},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u0.png"}},
{
          "id":"36772ad704df4968886e8b3bc4af16fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":60},
            "size":{
              "width":120,
              "height":720},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38973a78663546708aa27eed60fc7956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":60},
                "size":{
                  "width":120,
                  "height":720},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u2.png"}},
{
          "id":"c40cc6ecbe6f4a1e95bd7306c8ba7a81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":86},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6f8b51c54e408abcaa6c7eab881bbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":86},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u4.png"}},
{
          "id":"04f3c8e4fb0f434f8487697e2843b558",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":75,
              "y":150},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58b598400444567a476eb40585070ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":75,
                  "y":150},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76898c8f57c7492ba6fc0cebf3d12c6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":210},
            "size":{
              "width":22,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5857860de7f8457795d541d971645d6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":210},
                "size":{
                  "width":22,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u8.png"}},
{
          "id":"5ea474fb05ac4c6caae2d5d937b3f4af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":88,
              "y":208},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"becf31103c9c46edbabfd64d662587e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":208},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cde47d71047e407ab2332ccdc8ec59b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":88,
              "y":258},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e9c591596a4a6f9c4adb3173474d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":258},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1a553fea39143f382e049e72a2b7b44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":254},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f24913baea4e3394b6a5e45bf88a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":254},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u14.png"}},
{
          "id":"67d0ac5dce9040519bfe1a7be1f147aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":179},
            "size":{
              "width":1000,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者队列/u16_line.png"}},
{
          "id":"d7024fc804a04fad8d96f595f41c2d8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90.5},
            "size":{
              "width":22,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d046719630804cedb61719b6626f4626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90.5},
                "size":{
                  "width":22,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u8.png"}},
{
          "id":"4aa0b6b81132471088258462c9b3e968",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":218,
              "y":86},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af0e0978bd5400db947bf33115a136d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":86},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7f842518a1447f8a785a7d1a0bc4645",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":124,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e601a236b8484919969549ab5138d946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":124,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb632e7748f3406a9b8c9e41bbae1f71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":178},
            "size":{
              "width":140,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/患者队列/u23_line.png"}},
{
          "id":"4f1dd54d7dd1406981676793c1dd145a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":353,
              "y":150},
            "size":{
              "width":109,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3669fe71c6444dfeb3fb20aa3b853fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":353,
                  "y":150},
                "size":{
                  "width":109,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d6d14d013194d0fa714a07b0cdf9262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":496,
              "y":150},
            "size":{
              "width":109,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06267d525c54e60b67a9c3f4d2f54ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":150},
                "size":{
                  "width":109,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71578ff6a2ea4133a4361c640cc5b695",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":638,
              "y":150},
            "size":{
              "width":109,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7edc73004f4498b83286aabf98df078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":150},
                "size":{
                  "width":109,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70649fa0bbc9441c9e73f2c574d8f6f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":781,
              "y":150},
            "size":{
              "width":109,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a159816b7df4ac2b2695f5cbf8cd1e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":781,
                  "y":150},
                "size":{
                  "width":109,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba16bdbc5b5445a9454fbc0317ba8fb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":920,
              "y":149},
            "size":{
              "width":110,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3ac528f964ca4f53a8282b137d5ac322",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":243},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2431c09f43d8435fb91358121557ea24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":243},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"0fd8d2a4ad2047db9cd7a85a0681b0c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":248,
              "y":253},
            "size":{
              "width":91,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a072d965d6748f89d405cd12308f043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":248,
                  "y":253},
                "size":{
                  "width":91,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48a759e74cc34b34827274bcef34affb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":253},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1608ceeedcd64e6893fd7a0ae329592d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":253},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u37.png"}},
{
          "id":"028ab833f8d74064bd82b4885164ab81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":363},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"224453f4efaa4916844a6a434255a112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":363},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"5e6890442e46463e925a37381efcfae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":248,
              "y":373},
            "size":{
              "width":91,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1892cae9ae334896ae0b5009394fc5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":248,
                  "y":373},
                "size":{
                  "width":91,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"023a7ffdb2794fccbb339c80a5da2436",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":373},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e48fea4e554412a862c97590d34472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":373},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u43.png"}},
{
          "id":"3a1a536ed42649fd97ce2e88fc42b3fc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":198},
            "size":{
              "width":105,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者队列",
                      "target":{
                        "targetType":"page",
                        "url":"患者队列.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f36b1097896649b1805cb3afad67e82a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":247},
            "size":{
              "width":105,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的排班",
                      "target":{
                        "targetType":"page",
                        "url":"我的排班.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"85ef6016850c4bc384fe73fa318004a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1070,
              "y":130},
            "size":{
              "width":220,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccda42e9cb864286bfdf5812512afcc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1070,
                  "y":130},
                "size":{
                  "width":220,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u47.png"}},
{
          "id":"022e6acc81ee4e83bbb1dfbce55d9608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":243},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bbcad0bfc84fa2b973c8301b1069e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":475,
                  "y":243},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"e9074552cd454b35b7fed8b938b85ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":533,
              "y":253},
            "size":{
              "width":91,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53da214f5bfd49619ad00d184d7d3f04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":533,
                  "y":253},
                "size":{
                  "width":91,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20776bd5489d42f9bc41e29790a289df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":253},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c847e8cec7147cd8835342e67fc9f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":253},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u37.png"}},
{
          "id":"cbdb216d497c437b91248b6452eaba96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":243},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"202cd647b5674aa2a04074c987a4130e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":243},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"696cc9818913499f84316fc6b03f1a47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":818,
              "y":253},
            "size":{
              "width":77,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994ed35e2c0f4632864df6f25cb57f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":818,
                  "y":253},
                "size":{
                  "width":77,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05e8d4519acf4348830c8f8a79e07942",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":774,
              "y":253},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c05525e69c19448987783f5318fae2ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":774,
                  "y":253},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u43.png"}},
{
          "id":"1c66a957461e401e92d28f6d17a88316",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":363},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8f62d6dbe5949968c9a29ceb554f8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":475,
                  "y":363},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"b1bae9a28d3f476da4e1132308247728",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":533,
              "y":373},
            "size":{
              "width":105,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb73b5b2df734c3aaa0d9d71ee356623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":533,
                  "y":373},
                "size":{
                  "width":105,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e16f5844fb414fd69ed8dfc92a635569",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":373},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"042017422ff749cab5af1787e8b9c636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":373},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u37.png"}},
{
          "id":"5610f3d0de9044059f878c1bb58eb189",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":243},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 患者内页",
                      "target":{
                        "targetType":"page",
                        "url":"患者内页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"39abbd8025134522950de9bdf84566ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1070,
              "y":273},
            "size":{
              "width":220,
              "height":60},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"641bc25a08f34217afdb7994512cd374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1070,
                  "y":273},
                "size":{
                  "width":220,
                  "height":60},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u47.png"}},
{
          "id":"8b70ec09fe1348b4a83b29549b261249",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "paddingTop":"15",
            "location":{
              "x":362,
              "y":221},
            "size":{
              "width":34,
              "height":66},
            "rotation":"315",
            "textRotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937d69b0e5a144a48ed97083f6ac2845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "paddingTop":"15",
                "location":{
                  "x":362,
                  "y":221},
                "size":{
                  "width":34,
                  "height":66},
                "rotation":"315",
                "textRotation":"45",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u70.png"}},
{
          "id":"3b4c4a2c01c94d11a289b47f1b021b89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "paddingTop":"15",
            "location":{
              "x":646,
              "y":221},
            "size":{
              "width":34,
              "height":66},
            "rotation":"315",
            "textRotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f96fa47f4ca440c833fb3d7b6f276b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "paddingTop":"15",
                "location":{
                  "x":646,
                  "y":221},
                "size":{
                  "width":34,
                  "height":66},
                "rotation":"315",
                "textRotation":"45",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u70.png"}},
{
          "id":"612fa547c02545989e4abc06c4150049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":363},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41c986168d1442f3b23b0a323e9bd931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":363},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"3dafa827d4e949b2a18f5cd147ee008f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":818,
              "y":373},
            "size":{
              "width":91,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eb9afe729754dd5adaf0aff6a4eed46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":818,
                  "y":373},
                "size":{
                  "width":91,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74279b340f6b43c18f3f3ee0e5e53a24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":774,
              "y":373},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b7ce3ca5d1b47299f7e5eef4c8dee29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":774,
                  "y":373},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u37.png"}},
{
          "id":"fd0ea47fe2ae4a71864b462552a7a986",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":483},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae9aae31db04e5fb5f632e6b71de56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":483},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"80cb5705b786461cb1a3995bd5498ce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":248,
              "y":493},
            "size":{
              "width":91,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcdc6da1c7bd4b3bb0e0fad611f2a261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":248,
                  "y":493},
                "size":{
                  "width":91,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"137eafa597d44349839d60c77170e089",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":493},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"895929218bb44a56baa98882f12af8a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":493},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u37.png"}},
{
          "id":"a6be79d3d6d04875aef7ba889d0b5756",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":475,
              "y":483},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa4650b619e4498a5bce98172fd7fae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":475,
                  "y":483},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u33.png"}},
{
          "id":"34a156ccc3764fa59db9841ea6ba0aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":533,
              "y":493},
            "size":{
              "width":77,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85d0e7a5b504b56ae8f209ed393eb31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":533,
                  "y":493},
                "size":{
                  "width":77,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e1fdbed6b904449b0420a0448356e64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":493},
            "size":{
              "width":36,
              "height":53},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f034cb0ac36e4a128c7a21da01afaf2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":493},
                "size":{
                  "width":36,
                  "height":53},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u43.png"}},
{
          "id":"0f8efa20278b44148f7f704af7ca563b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "location":{
              "x":190,
              "y":208},
            "size":{
              "width":140,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c0298ada6f48c3b8d3298d90663c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":208},
                "size":{
                  "width":140,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"2d34edf92649464ab1daaa7500172f86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":1070,
              "y":350},
            "size":{
              "width":220,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa576ef728a46e09fc5ded83a9171b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":1070,
                  "y":350},
                "size":{
                  "width":220,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/患者队列/u94.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "83e95a882326406dbeabc3dc65768974":{
      "scriptId":"u0"},
    "370ce8ab2b05414cb403d6c5ea11c43c":{
      "scriptId":"u1"},
    "36772ad704df4968886e8b3bc4af16fd":{
      "scriptId":"u2"},
    "38973a78663546708aa27eed60fc7956":{
      "scriptId":"u3"},
    "c40cc6ecbe6f4a1e95bd7306c8ba7a81":{
      "scriptId":"u4"},
    "dc6f8b51c54e408abcaa6c7eab881bbd":{
      "scriptId":"u5"},
    "04f3c8e4fb0f434f8487697e2843b558":{
      "scriptId":"u6"},
    "c58b598400444567a476eb40585070ca":{
      "scriptId":"u7"},
    "76898c8f57c7492ba6fc0cebf3d12c6e":{
      "scriptId":"u8"},
    "5857860de7f8457795d541d971645d6a":{
      "scriptId":"u9"},
    "5ea474fb05ac4c6caae2d5d937b3f4af":{
      "scriptId":"u10"},
    "becf31103c9c46edbabfd64d662587e5":{
      "scriptId":"u11"},
    "cde47d71047e407ab2332ccdc8ec59b1":{
      "scriptId":"u12"},
    "a9e9c591596a4a6f9c4adb3173474d65":{
      "scriptId":"u13"},
    "f1a553fea39143f382e049e72a2b7b44":{
      "scriptId":"u14"},
    "67f24913baea4e3394b6a5e45bf88a2b":{
      "scriptId":"u15"},
    "67d0ac5dce9040519bfe1a7be1f147aa":{
      "scriptId":"u16"},
    "d7024fc804a04fad8d96f595f41c2d8f":{
      "scriptId":"u17"},
    "d046719630804cedb61719b6626f4626":{
      "scriptId":"u18"},
    "4aa0b6b81132471088258462c9b3e968":{
      "scriptId":"u19"},
    "2af0e0978bd5400db947bf33115a136d":{
      "scriptId":"u20"},
    "f7f842518a1447f8a785a7d1a0bc4645":{
      "scriptId":"u21"},
    "e601a236b8484919969549ab5138d946":{
      "scriptId":"u22"},
    "fb632e7748f3406a9b8c9e41bbae1f71":{
      "scriptId":"u23"},
    "4f1dd54d7dd1406981676793c1dd145a":{
      "scriptId":"u24"},
    "3669fe71c6444dfeb3fb20aa3b853fd2":{
      "scriptId":"u25"},
    "2d6d14d013194d0fa714a07b0cdf9262":{
      "scriptId":"u26"},
    "c06267d525c54e60b67a9c3f4d2f54ef":{
      "scriptId":"u27"},
    "71578ff6a2ea4133a4361c640cc5b695":{
      "scriptId":"u28"},
    "a7edc73004f4498b83286aabf98df078":{
      "scriptId":"u29"},
    "70649fa0bbc9441c9e73f2c574d8f6f3":{
      "scriptId":"u30"},
    "0a159816b7df4ac2b2695f5cbf8cd1e2":{
      "scriptId":"u31"},
    "0ba16bdbc5b5445a9454fbc0317ba8fb":{
      "scriptId":"u32"},
    "3ac528f964ca4f53a8282b137d5ac322":{
      "scriptId":"u33"},
    "2431c09f43d8435fb91358121557ea24":{
      "scriptId":"u34"},
    "0fd8d2a4ad2047db9cd7a85a0681b0c7":{
      "scriptId":"u35"},
    "5a072d965d6748f89d405cd12308f043":{
      "scriptId":"u36"},
    "48a759e74cc34b34827274bcef34affb":{
      "scriptId":"u37"},
    "1608ceeedcd64e6893fd7a0ae329592d":{
      "scriptId":"u38"},
    "028ab833f8d74064bd82b4885164ab81":{
      "scriptId":"u39"},
    "224453f4efaa4916844a6a434255a112":{
      "scriptId":"u40"},
    "5e6890442e46463e925a37381efcfae0":{
      "scriptId":"u41"},
    "1892cae9ae334896ae0b5009394fc5cf":{
      "scriptId":"u42"},
    "023a7ffdb2794fccbb339c80a5da2436":{
      "scriptId":"u43"},
    "71e48fea4e554412a862c97590d34472":{
      "scriptId":"u44"},
    "3a1a536ed42649fd97ce2e88fc42b3fc":{
      "scriptId":"u45"},
    "f36b1097896649b1805cb3afad67e82a":{
      "scriptId":"u46"},
    "85ef6016850c4bc384fe73fa318004a2":{
      "scriptId":"u47"},
    "ccda42e9cb864286bfdf5812512afcc2":{
      "scriptId":"u48"},
    "022e6acc81ee4e83bbb1dfbce55d9608":{
      "scriptId":"u49"},
    "b1bbcad0bfc84fa2b973c8301b1069e5":{
      "scriptId":"u50"},
    "e9074552cd454b35b7fed8b938b85ebe":{
      "scriptId":"u51"},
    "53da214f5bfd49619ad00d184d7d3f04":{
      "scriptId":"u52"},
    "20776bd5489d42f9bc41e29790a289df":{
      "scriptId":"u53"},
    "7c847e8cec7147cd8835342e67fc9f77":{
      "scriptId":"u54"},
    "cbdb216d497c437b91248b6452eaba96":{
      "scriptId":"u55"},
    "202cd647b5674aa2a04074c987a4130e":{
      "scriptId":"u56"},
    "696cc9818913499f84316fc6b03f1a47":{
      "scriptId":"u57"},
    "994ed35e2c0f4632864df6f25cb57f51":{
      "scriptId":"u58"},
    "05e8d4519acf4348830c8f8a79e07942":{
      "scriptId":"u59"},
    "c05525e69c19448987783f5318fae2ba":{
      "scriptId":"u60"},
    "1c66a957461e401e92d28f6d17a88316":{
      "scriptId":"u61"},
    "e8f62d6dbe5949968c9a29ceb554f8ee":{
      "scriptId":"u62"},
    "b1bae9a28d3f476da4e1132308247728":{
      "scriptId":"u63"},
    "bb73b5b2df734c3aaa0d9d71ee356623":{
      "scriptId":"u64"},
    "e16f5844fb414fd69ed8dfc92a635569":{
      "scriptId":"u65"},
    "042017422ff749cab5af1787e8b9c636":{
      "scriptId":"u66"},
    "5610f3d0de9044059f878c1bb58eb189":{
      "scriptId":"u67"},
    "39abbd8025134522950de9bdf84566ee":{
      "scriptId":"u68"},
    "641bc25a08f34217afdb7994512cd374":{
      "scriptId":"u69"},
    "8b70ec09fe1348b4a83b29549b261249":{
      "scriptId":"u70"},
    "937d69b0e5a144a48ed97083f6ac2845":{
      "scriptId":"u71"},
    "3b4c4a2c01c94d11a289b47f1b021b89":{
      "scriptId":"u72"},
    "9f96fa47f4ca440c833fb3d7b6f276b6":{
      "scriptId":"u73"},
    "612fa547c02545989e4abc06c4150049":{
      "scriptId":"u74"},
    "41c986168d1442f3b23b0a323e9bd931":{
      "scriptId":"u75"},
    "3dafa827d4e949b2a18f5cd147ee008f":{
      "scriptId":"u76"},
    "6eb9afe729754dd5adaf0aff6a4eed46":{
      "scriptId":"u77"},
    "74279b340f6b43c18f3f3ee0e5e53a24":{
      "scriptId":"u78"},
    "3b7ce3ca5d1b47299f7e5eef4c8dee29":{
      "scriptId":"u79"},
    "fd0ea47fe2ae4a71864b462552a7a986":{
      "scriptId":"u80"},
    "cae9aae31db04e5fb5f632e6b71de56d":{
      "scriptId":"u81"},
    "80cb5705b786461cb1a3995bd5498ce7":{
      "scriptId":"u82"},
    "dcdc6da1c7bd4b3bb0e0fad611f2a261":{
      "scriptId":"u83"},
    "137eafa597d44349839d60c77170e089":{
      "scriptId":"u84"},
    "895929218bb44a56baa98882f12af8a1":{
      "scriptId":"u85"},
    "a6be79d3d6d04875aef7ba889d0b5756":{
      "scriptId":"u86"},
    "afa4650b619e4498a5bce98172fd7fae":{
      "scriptId":"u87"},
    "34a156ccc3764fa59db9841ea6ba0aa1":{
      "scriptId":"u88"},
    "d85d0e7a5b504b56ae8f209ed393eb31":{
      "scriptId":"u89"},
    "5e1fdbed6b904449b0420a0448356e64":{
      "scriptId":"u90"},
    "f034cb0ac36e4a128c7a21da01afaf2f":{
      "scriptId":"u91"},
    "0f8efa20278b44148f7f704af7ca563b":{
      "scriptId":"u92"},
    "54c0298ada6f48c3b8d3298d90663c9f":{
      "scriptId":"u93"},
    "2d34edf92649464ab1daaa7500172f86":{
      "scriptId":"u94"},
    "2aa576ef728a46e09fc5ded83a9171b1":{
      "scriptId":"u95"}}});