$axure.loadCurrentPage({
  "url":"选择房间.html",
  "generationDate":new Date(1451924402393.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6426f686b8cf471c9acaf0fc2ed0c987",
    "type":"Axure:Page",
    "name":"选择房间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a5daea0177ef48e39bce8de0b183dba5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705ff5d6a4d24020befc90df33ef552e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u0.png"}},
{
          "id":"4eb8f0c1099c4e8cb98652d1635f9f53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1025},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd72dfcdee44e40ae78df328f25ecca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1025},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u2.png"}},
{
          "id":"960ba2b0fda042c7a08394d55398bbbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":190,
              "y":143},
            "size":{
              "width":37,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"989f82841f9a4493b1020131a5741cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":190,
                  "y":143},
                "size":{
                  "width":37,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76fdeaccc9be4d188f0f3d10b69b2f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":560,
              "y":143},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2965122362e74cd5a2df9e0837a033e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":560,
                  "y":143},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b4ffb41b5424d38822235005ff71f4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":75,
              "y":184},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7298ce6f1e22496fba7c0f97bf7e3a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":184},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23b52bc510734c49ab2ca0ae9d8948cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":75,
              "y":307},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc8230e1ebe4c5780e7d092e35789ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":307},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af3d276683184b46889e18741c8a92cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":75,
              "y":473},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09f9e2a8acfa4cd485d0ad920fc0e8a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":473},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c58d04617b754d0795677e23e31689b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":221},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0e92f7688847498eb985fb059ab6fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":221},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0f0b78f8193441ea6d0358de11101ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":265},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad4ebce532442f8bc617aa88c842d87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":265},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec36e29ba5db4e33b7ee845c43de637e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":388},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a7e34bc01a4f8892ddaf6a4b593bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":388},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f6025aa27124e54b3ea1203d8af186d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":346},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"882b1da0aa464bba8a37007244e7ac93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":346},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61e73669840a44ec85cc5cc4f52168d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":432},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ee7e77dbae40c197ef4a20f664cc24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":432},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af47031704ea41c88c5b3796f30d610d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":512},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c9ec098c6e49ea9917a186dfeacf87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":512},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39eae1064e2948b9ba8485af7df7f8f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":75,
              "y":554},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27a05f03c7914057afa580b5bfb7b2ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":554},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e20606763e5f471394f61c0f7d19c4aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":75,
              "y":599},
            "size":{
              "width":28,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd731240aad4e18b74323404dc31143",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":75,
                  "y":599},
                "size":{
                  "width":28,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"862908fcf0634f5881bd30d4567e88d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":220},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab8a03a7ce943ddbc966b4b6fcf1d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":220},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户预约（微信）/u16.png"}},
{
          "id":"393f5ddb53ea49a384e466e0731170a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":265},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1da1d7c1708a4027aac8f08671e25205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":265},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户预约（微信）/u293.png"}},
{
          "id":"dce4f679075b4133a7c68bba0ab364c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":222},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b8f745973da4b9bb0bf59fc36b99f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":222},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"398f1523f28c4a89b8f4a4cf577951ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":266},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f605e3e575184ba0ab57f93568b47e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":266},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4789c7b447d94ab6ba99e3a16b0ad2f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":347},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bac5e15a66043b8be61401af9c34986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":347},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97dc6aad792642fea17a8cca5651dcf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":389},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e76d6e9bc8748f99c7212bf3af4c8b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":389},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33938706ca2c40b3b95100451c50908d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":433},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14fa58452662476bb38512d33477b64d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":433},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65ff0c8fca874924b537defcdfcea52c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":513},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82c7700dcb354da285a11ec47aa1eb02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":513},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13666cd3bcae419aab5941b171a5bf4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":134,
              "y":555},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b605432d112540eb9260b9d8f61581f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":555},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"847913b8a21c4644a9edc863951de97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":134,
              "y":600},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f56dbd04e5495694bbec173d5059d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":600},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ffcfa4901a247028c6365bb310d6580",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":343},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fafe7dc0da54422d8faa05500df2ac79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":343},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户预约（微信）/u16.png"}},
{
          "id":"b89ab18db73d43cf9abb1cb5f368b65f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":429},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af2085a3e78490fbc304aec9a7ec10a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":429},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u52.png"}},
{
          "id":"e5665d213c54481fa4bca0095c844eb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":388},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61af6e7b0dbe4437aec470d260e1bd2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":388},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户预约（微信）/u293.png"}},
{
          "id":"9ec7c88e053445cf98422ec090a38a50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":598},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9173a1b6d4c4942b3297719929b8776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":598},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u52.png"}},
{
          "id":"c62ad6b9e91246a796b55f4250bb2525",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":195},
            "size":{
              "width":439,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"838406448b6941188faaf47d557d4212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":195},
                "size":{
                  "width":439,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u58.png"}},
{
          "id":"6c751c2327454470860d2b8a5bc2acd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":403,
              "y":221},
            "size":{
              "width":157,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4566a90ff1d14c6fab34cc92e6d9086e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":403,
                  "y":221},
                "size":{
                  "width":157,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"569ec697fe1a40e58a9218288469196e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":403,
              "y":265},
            "size":{
              "width":157,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2871930b48e34d3a9442e27fe8763414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":403,
                  "y":265},
                "size":{
                  "width":157,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59c4f5076f1f4db6a901b4aba27352a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":403,
              "y":309},
            "size":{
              "width":157,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f9d162c97d646479e1973b80dcbbae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":403,
                  "y":309},
                "size":{
                  "width":157,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a43cc8a827045239cb98b78057076d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":403,
              "y":352},
            "size":{
              "width":157,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f164b166f4a4329bc6f0bb00cb2ac38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":403,
                  "y":352},
                "size":{
                  "width":157,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69d544f43d8749e285d27ccf53a77237",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":144},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca3288ec2e849e38af79e0d786ffe21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":144},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 输入个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"输入个人信息_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/输入个人信息/u16.png"}},
{
          "id":"28e4f15a319a4223ada71396bcf436db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":725,
              "y":220},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef6ae88e85d6439098623965a9e83bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":725,
                  "y":220},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6cd26ac44df43179fb2865805697a47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":703,
              "y":264},
            "size":{
              "width":65,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfdfb73873e64b1fbf74e8eae90206ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":703,
                  "y":264},
                "size":{
                  "width":65,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b317ca68189d496bbf891af71d143869",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":695,
              "y":308},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cc9ff6e0994cfcab362cfa25c6e87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":308},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acf69f81403c4219a3f6d8c5a41052ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":695,
              "y":352},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf1c635c49a04ec2894bac64b357bbb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":695,
                  "y":352},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"848a5be1b86f44b594c08b7672f1ed9e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":270},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c71d876f5744e48cc1e4134882dc76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":270},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"d63465ca52254db09f8190cea18894af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1710,
              "y":380},
            "size":{
              "width":270,
              "height":179},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d03fbde1dd4dd7966893a427d5cd8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1710,
                  "y":380},
                "size":{
                  "width":270,
                  "height":179},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u80.png"}},
{
          "id":"bbe8c5a602584cdf867ee7eade048830",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1710,
              "y":511},
            "size":{
              "width":270,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择医师和时间/u82_line.png"}},
{
          "id":"51e850ef699b42e8a01dd3292371a41a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"center",
            "location":{
              "x":1724,
              "y":410},
            "size":{
              "width":243,
              "height":72},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94416924763c408a9557aa617f66113a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "location":{
                  "x":1724,
                  "y":410},
                "size":{
                  "width":243,
                  "height":72},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22f53adaedfa420c922b5cd8ebdcc8ac",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1805,
              "y":526},
            "size":{
              "width":81,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11a36251a0a7476ba332ac476c2b713c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1805,
                  "y":526},
                "size":{
                  "width":81,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0a0868c3b6f47fcaf0fd4b5c8d52240",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1320,
              "y":380},
            "size":{
              "width":330,
              "height":179},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0326ba164ca24fb8b107e734b2b0680b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1320,
                  "y":380},
                "size":{
                  "width":330,
                  "height":179},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择医师和时间/u87.png"}},
{
          "id":"7d5d0da256a84c57874bae87cb03ff29",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1320,
              "y":511},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择医师和时间/u89_line.png"}},
{
          "id":"e8af76e35193456891af996576658ead",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1484,
              "y":516},
            "size":{
              "width":10,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择医师和时间/u90_line.png"}},
{
          "id":"351db93ba31240d8abf8ac14160cf4fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "lineSpacing":"28px",
            "location":{
              "x":1340,
              "y":391},
            "size":{
              "width":297,
              "height":112},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"820133911b6041a6acfa9c2f35a1eb1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "lineSpacing":"28px",
                "location":{
                  "x":1340,
                  "y":391},
                "size":{
                  "width":297,
                  "height":112},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"621ea2b9dc614c42ae85957e95e3758a",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1548,
              "y":526},
            "size":{
              "width":44,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a405a36014a47c2901315952ff1cf51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1548,
                  "y":526},
                "size":{
                  "width":44,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76846e6dca044865bedf0e9badb09907",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1359,
              "y":526},
            "size":{
              "width":78,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c398b9aa259d4510817fd4d5a76ac35b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1359,
                  "y":526},
                "size":{
                  "width":78,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00dbb8dd296e454d8d3856b6b35983fc",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1660,
              "y":460},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8fe7527e52142a991097735577aaac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1660,
                  "y":460},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"f08225d42a1840fdacad34aeba290992",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":380},
            "size":{
              "width":274,
              "height":199},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bffdd58da6ca4135ac0cfd2962289518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":380},
                "size":{
                  "width":274,
                  "height":199},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择房间/u99.png"}},
{
          "id":"96d96f67a1544c17bc2213c4bba07569",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":531},
            "size":{
              "width":274,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择房间/u101_line.png"}},
{
          "id":"75ead68978d24fbe96a7ca5be98f281a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1116,
              "y":536},
            "size":{
              "width":10,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择医师和时间/u90_line.png"}},
{
          "id":"dc9f258e99384711a971ece1544454c5",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1169,
              "y":546},
            "size":{
              "width":37,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4511c946db7042afa813ddcde07748e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1169,
                  "y":546},
                "size":{
                  "width":37,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6945508445314dc0b1b6b67ff3c9dbb0",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":1012,
              "y":546},
            "size":{
              "width":65,
              "height":21},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f1237ae69b04c38b0fd3934701bd6d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":1012,
                  "y":546},
                "size":{
                  "width":65,
                  "height":21},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71b7c95b87b04b0c8ed70c763cee9082",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1264,
              "y":460},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d3dcd78b8a4104a92c613264751bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1264,
                  "y":460},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb363bebd4f74dadbb397aec6886d5a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1046.5,
              "y":391},
            "size":{
              "width":141,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d0829c4d8646708b37c24f235cc477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1046.5,
                  "y":391},
                "size":{
                  "width":141,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择房间/u109.png"}},
{
          "id":"346707e12ad24492a58c5dae6bef4c0b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":429},
            "size":{
              "width":274,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择房间/u111_line.png"}},
{
          "id":"26127d0b804241a89dd5e229ae01eaa6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":459},
            "size":{
              "width":274,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择房间/u111_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a5daea0177ef48e39bce8de0b183dba5":{
      "scriptId":"u0"},
    "705ff5d6a4d24020befc90df33ef552e":{
      "scriptId":"u1"},
    "4eb8f0c1099c4e8cb98652d1635f9f53":{
      "scriptId":"u2"},
    "fcd72dfcdee44e40ae78df328f25ecca":{
      "scriptId":"u3"},
    "960ba2b0fda042c7a08394d55398bbbd":{
      "scriptId":"u4"},
    "989f82841f9a4493b1020131a5741cb3":{
      "scriptId":"u5"},
    "76fdeaccc9be4d188f0f3d10b69b2f32":{
      "scriptId":"u6"},
    "2965122362e74cd5a2df9e0837a033e4":{
      "scriptId":"u7"},
    "2b4ffb41b5424d38822235005ff71f4c":{
      "scriptId":"u8"},
    "7298ce6f1e22496fba7c0f97bf7e3a91":{
      "scriptId":"u9"},
    "23b52bc510734c49ab2ca0ae9d8948cf":{
      "scriptId":"u10"},
    "7cc8230e1ebe4c5780e7d092e35789ae":{
      "scriptId":"u11"},
    "af3d276683184b46889e18741c8a92cc":{
      "scriptId":"u12"},
    "09f9e2a8acfa4cd485d0ad920fc0e8a3":{
      "scriptId":"u13"},
    "c58d04617b754d0795677e23e31689b0":{
      "scriptId":"u14"},
    "7a0e92f7688847498eb985fb059ab6fc":{
      "scriptId":"u15"},
    "d0f0b78f8193441ea6d0358de11101ff":{
      "scriptId":"u16"},
    "2ad4ebce532442f8bc617aa88c842d87":{
      "scriptId":"u17"},
    "ec36e29ba5db4e33b7ee845c43de637e":{
      "scriptId":"u18"},
    "39a7e34bc01a4f8892ddaf6a4b593bc2":{
      "scriptId":"u19"},
    "1f6025aa27124e54b3ea1203d8af186d":{
      "scriptId":"u20"},
    "882b1da0aa464bba8a37007244e7ac93":{
      "scriptId":"u21"},
    "61e73669840a44ec85cc5cc4f52168d7":{
      "scriptId":"u22"},
    "70ee7e77dbae40c197ef4a20f664cc24":{
      "scriptId":"u23"},
    "af47031704ea41c88c5b3796f30d610d":{
      "scriptId":"u24"},
    "96c9ec098c6e49ea9917a186dfeacf87":{
      "scriptId":"u25"},
    "39eae1064e2948b9ba8485af7df7f8f9":{
      "scriptId":"u26"},
    "27a05f03c7914057afa580b5bfb7b2ad":{
      "scriptId":"u27"},
    "e20606763e5f471394f61c0f7d19c4aa":{
      "scriptId":"u28"},
    "7bd731240aad4e18b74323404dc31143":{
      "scriptId":"u29"},
    "862908fcf0634f5881bd30d4567e88d5":{
      "scriptId":"u30"},
    "7ab8a03a7ce943ddbc966b4b6fcf1d17":{
      "scriptId":"u31"},
    "393f5ddb53ea49a384e466e0731170a4":{
      "scriptId":"u32"},
    "1da1d7c1708a4027aac8f08671e25205":{
      "scriptId":"u33"},
    "dce4f679075b4133a7c68bba0ab364c7":{
      "scriptId":"u34"},
    "1b8f745973da4b9bb0bf59fc36b99f14":{
      "scriptId":"u35"},
    "398f1523f28c4a89b8f4a4cf577951ac":{
      "scriptId":"u36"},
    "f605e3e575184ba0ab57f93568b47e5a":{
      "scriptId":"u37"},
    "4789c7b447d94ab6ba99e3a16b0ad2f5":{
      "scriptId":"u38"},
    "6bac5e15a66043b8be61401af9c34986":{
      "scriptId":"u39"},
    "97dc6aad792642fea17a8cca5651dcf8":{
      "scriptId":"u40"},
    "1e76d6e9bc8748f99c7212bf3af4c8b0":{
      "scriptId":"u41"},
    "33938706ca2c40b3b95100451c50908d":{
      "scriptId":"u42"},
    "14fa58452662476bb38512d33477b64d":{
      "scriptId":"u43"},
    "65ff0c8fca874924b537defcdfcea52c":{
      "scriptId":"u44"},
    "82c7700dcb354da285a11ec47aa1eb02":{
      "scriptId":"u45"},
    "13666cd3bcae419aab5941b171a5bf4d":{
      "scriptId":"u46"},
    "b605432d112540eb9260b9d8f61581f7":{
      "scriptId":"u47"},
    "847913b8a21c4644a9edc863951de97a":{
      "scriptId":"u48"},
    "c5f56dbd04e5495694bbec173d5059d4":{
      "scriptId":"u49"},
    "2ffcfa4901a247028c6365bb310d6580":{
      "scriptId":"u50"},
    "fafe7dc0da54422d8faa05500df2ac79":{
      "scriptId":"u51"},
    "b89ab18db73d43cf9abb1cb5f368b65f":{
      "scriptId":"u52"},
    "8af2085a3e78490fbc304aec9a7ec10a":{
      "scriptId":"u53"},
    "e5665d213c54481fa4bca0095c844eb1":{
      "scriptId":"u54"},
    "61af6e7b0dbe4437aec470d260e1bd2b":{
      "scriptId":"u55"},
    "9ec7c88e053445cf98422ec090a38a50":{
      "scriptId":"u56"},
    "b9173a1b6d4c4942b3297719929b8776":{
      "scriptId":"u57"},
    "c62ad6b9e91246a796b55f4250bb2525":{
      "scriptId":"u58"},
    "838406448b6941188faaf47d557d4212":{
      "scriptId":"u59"},
    "6c751c2327454470860d2b8a5bc2acd9":{
      "scriptId":"u60"},
    "4566a90ff1d14c6fab34cc92e6d9086e":{
      "scriptId":"u61"},
    "569ec697fe1a40e58a9218288469196e":{
      "scriptId":"u62"},
    "2871930b48e34d3a9442e27fe8763414":{
      "scriptId":"u63"},
    "59c4f5076f1f4db6a901b4aba27352a1":{
      "scriptId":"u64"},
    "1f9d162c97d646479e1973b80dcbbae4":{
      "scriptId":"u65"},
    "7a43cc8a827045239cb98b78057076d2":{
      "scriptId":"u66"},
    "0f164b166f4a4329bc6f0bb00cb2ac38":{
      "scriptId":"u67"},
    "69d544f43d8749e285d27ccf53a77237":{
      "scriptId":"u68"},
    "0ca3288ec2e849e38af79e0d786ffe21":{
      "scriptId":"u69"},
    "28e4f15a319a4223ada71396bcf436db":{
      "scriptId":"u70"},
    "ef6ae88e85d6439098623965a9e83bfd":{
      "scriptId":"u71"},
    "e6cd26ac44df43179fb2865805697a47":{
      "scriptId":"u72"},
    "cfdfb73873e64b1fbf74e8eae90206ab":{
      "scriptId":"u73"},
    "b317ca68189d496bbf891af71d143869":{
      "scriptId":"u74"},
    "d1cc9ff6e0994cfcab362cfa25c6e87d":{
      "scriptId":"u75"},
    "acf69f81403c4219a3f6d8c5a41052ac":{
      "scriptId":"u76"},
    "bf1c635c49a04ec2894bac64b357bbb4":{
      "scriptId":"u77"},
    "848a5be1b86f44b594c08b7672f1ed9e":{
      "scriptId":"u78"},
    "29c71d876f5744e48cc1e4134882dc76":{
      "scriptId":"u79"},
    "d63465ca52254db09f8190cea18894af":{
      "scriptId":"u80"},
    "f9d03fbde1dd4dd7966893a427d5cd8e":{
      "scriptId":"u81"},
    "bbe8c5a602584cdf867ee7eade048830":{
      "scriptId":"u82"},
    "51e850ef699b42e8a01dd3292371a41a":{
      "scriptId":"u83"},
    "94416924763c408a9557aa617f66113a":{
      "scriptId":"u84"},
    "22f53adaedfa420c922b5cd8ebdcc8ac":{
      "scriptId":"u85"},
    "11a36251a0a7476ba332ac476c2b713c":{
      "scriptId":"u86"},
    "a0a0868c3b6f47fcaf0fd4b5c8d52240":{
      "scriptId":"u87"},
    "0326ba164ca24fb8b107e734b2b0680b":{
      "scriptId":"u88"},
    "7d5d0da256a84c57874bae87cb03ff29":{
      "scriptId":"u89"},
    "e8af76e35193456891af996576658ead":{
      "scriptId":"u90"},
    "351db93ba31240d8abf8ac14160cf4fa":{
      "scriptId":"u91"},
    "820133911b6041a6acfa9c2f35a1eb1c":{
      "scriptId":"u92"},
    "621ea2b9dc614c42ae85957e95e3758a":{
      "scriptId":"u93"},
    "6a405a36014a47c2901315952ff1cf51":{
      "scriptId":"u94"},
    "76846e6dca044865bedf0e9badb09907":{
      "scriptId":"u95"},
    "c398b9aa259d4510817fd4d5a76ac35b":{
      "scriptId":"u96"},
    "00dbb8dd296e454d8d3856b6b35983fc":{
      "scriptId":"u97"},
    "c8fe7527e52142a991097735577aaac0":{
      "scriptId":"u98"},
    "f08225d42a1840fdacad34aeba290992":{
      "scriptId":"u99"},
    "bffdd58da6ca4135ac0cfd2962289518":{
      "scriptId":"u100"},
    "96d96f67a1544c17bc2213c4bba07569":{
      "scriptId":"u101"},
    "75ead68978d24fbe96a7ca5be98f281a":{
      "scriptId":"u102"},
    "dc9f258e99384711a971ece1544454c5":{
      "scriptId":"u103"},
    "4511c946db7042afa813ddcde07748e2":{
      "scriptId":"u104"},
    "6945508445314dc0b1b6b67ff3c9dbb0":{
      "scriptId":"u105"},
    "1f1237ae69b04c38b0fd3934701bd6d3":{
      "scriptId":"u106"},
    "71b7c95b87b04b0c8ed70c763cee9082":{
      "scriptId":"u107"},
    "17d3dcd78b8a4104a92c613264751bb6":{
      "scriptId":"u108"},
    "bb363bebd4f74dadbb397aec6886d5a9":{
      "scriptId":"u109"},
    "b7d0829c4d8646708b37c24f235cc477":{
      "scriptId":"u110"},
    "346707e12ad24492a58c5dae6bef4c0b":{
      "scriptId":"u111"},
    "26127d0b804241a89dd5e229ae01eaa6":{
      "scriptId":"u112"}}});