$axure.loadCurrentPage({
  "url":"导诊.html",
  "generationDate":new Date(1449523427502),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aeb3f83534cd4055ad26bef0ba3855c9",
    "type":"Axure:Page",
    "name":"导诊",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73923a6d3a034f49b0d093ba0a1731a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5544fa99e7ad4d478068c26efc855b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u0.png"}},
{
          "id":"149567f5e1df44898e57112158cb4460",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1026},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9eb748bf6f04ac7a11b7b6486a822a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1026},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u2.png"}},
{
          "id":"44fee49892ed448ab3f3e58578cccfca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":158,
              "y":430},
            "size":{
              "width":220,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ce03124118447cb6c74a0220f4a988",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":158,
                  "y":430},
                "size":{
                  "width":220,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 现场挂号",
                      "target":{
                        "targetType":"page",
                        "url":"现场挂号.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/导诊/u4.png"}},
{
          "id":"0051deea949d4c75901fce1b48d9a099",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":498,
              "y":430},
            "size":{
              "width":220,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41094ad1d9f7400a87d412731165ab4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":498,
                  "y":430},
                "size":{
                  "width":220,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u4.png"}},
{
          "id":"05b0b165e3b44d048faf04e62f39adda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":699,
              "y":412},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e3f0abbe9e64fcbbfd372400291239c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":699,
                  "y":412},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u8.png"}},
{
          "id":"9c4a35cbf5c24698bd83d2fcab741bd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":741,
              "y":412},
            "size":{
              "width":157,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bd44deb3c84c1f98c0c1c9ec597e03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":741,
                  "y":412},
                "size":{
                  "width":157,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u10.png"}},
{
          "id":"26b3f1c9711d45e49102def9e45de5ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1062},
            "size":{
              "width":769,
              "height":77},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a89e90981fa4d6891a587bc678e48f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1062},
                "size":{
                  "width":769,
                  "height":77},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u12.png"}},
{
          "id":"713eef05023d46b1b5e2e018db6c9478",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0219fadfdf4bf382df29050ff8fdf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u14.png"}},
{
          "id":"055fdc1d11284329aca4ec6a23d378f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":113},
            "size":{
              "width":100,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875a2ac3884544babeda252d74cc5157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":113},
                "size":{
                  "width":100,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u16.png"}},
{
          "id":"b50c1989ea8b4084848c7cf360fd0af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":390,
              "y":143},
            "size":{
              "width":109,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c9bbfa6cb1435788f0075d66cd68d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":390,
                  "y":143},
                "size":{
                  "width":109,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9836cad72ff4080bd431beb8c8cbc50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":769,
              "y":146},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e97df936c5864f9c881f63cecf14bc92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":769,
                  "y":146},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"937f47c8a1a24b2c91ea5658c5f16f50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":1090},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01921ba7a9954cea950844de72045500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":1090},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊/u22.png"}},
{
          "id":"1a1114e5ff2445fb807ace9c2675522d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":418,
              "y":1119},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f217501c764228a3111fcc31d854dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":418,
                  "y":1119},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "73923a6d3a034f49b0d093ba0a1731a9":{
      "scriptId":"u0"},
    "5544fa99e7ad4d478068c26efc855b91":{
      "scriptId":"u1"},
    "149567f5e1df44898e57112158cb4460":{
      "scriptId":"u2"},
    "b9eb748bf6f04ac7a11b7b6486a822a2":{
      "scriptId":"u3"},
    "44fee49892ed448ab3f3e58578cccfca":{
      "scriptId":"u4"},
    "33ce03124118447cb6c74a0220f4a988":{
      "scriptId":"u5"},
    "0051deea949d4c75901fce1b48d9a099":{
      "scriptId":"u6"},
    "41094ad1d9f7400a87d412731165ab4f":{
      "scriptId":"u7"},
    "05b0b165e3b44d048faf04e62f39adda":{
      "scriptId":"u8"},
    "7e3f0abbe9e64fcbbfd372400291239c":{
      "scriptId":"u9"},
    "9c4a35cbf5c24698bd83d2fcab741bd9":{
      "scriptId":"u10"},
    "23bd44deb3c84c1f98c0c1c9ec597e03":{
      "scriptId":"u11"},
    "26b3f1c9711d45e49102def9e45de5ee":{
      "scriptId":"u12"},
    "4a89e90981fa4d6891a587bc678e48f8":{
      "scriptId":"u13"},
    "713eef05023d46b1b5e2e018db6c9478":{
      "scriptId":"u14"},
    "7b0219fadfdf4bf382df29050ff8fdf3":{
      "scriptId":"u15"},
    "055fdc1d11284329aca4ec6a23d378f8":{
      "scriptId":"u16"},
    "875a2ac3884544babeda252d74cc5157":{
      "scriptId":"u17"},
    "b50c1989ea8b4084848c7cf360fd0af3":{
      "scriptId":"u18"},
    "c9c9bbfa6cb1435788f0075d66cd68d3":{
      "scriptId":"u19"},
    "d9836cad72ff4080bd431beb8c8cbc50":{
      "scriptId":"u20"},
    "e97df936c5864f9c881f63cecf14bc92":{
      "scriptId":"u21"},
    "937f47c8a1a24b2c91ea5658c5f16f50":{
      "scriptId":"u22"},
    "01921ba7a9954cea950844de72045500":{
      "scriptId":"u23"},
    "1a1114e5ff2445fb807ace9c2675522d":{
      "scriptId":"u24"},
    "54f217501c764228a3111fcc31d854dc":{
      "scriptId":"u25"}}});