$axure.loadCurrentPage({
  "url":"输入个人信息_1.html",
  "generationDate":new Date(1451924402268.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f3d40edf3fa04d6b81108945e1ccee05",
    "type":"Axure:Page",
    "name":"输入个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7aae74b4b9264b7e8048db8d442c11de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":889,
              "height":1254}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f83ec0768ed4e1f9d489422a5e79df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":889,
                  "height":1254}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u0.png"}},
{
          "id":"77b283ab6e394761b9240d4093b61e20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":1026},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2768c32ff8a548e898d387e9a0a22170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":1026},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u2.png"}},
{
          "id":"11fa37bf5610496289079fc21c6dd6cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1062},
            "size":{
              "width":769,
              "height":77},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f81aa683cc84c028a7e7d597c37ee62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1062},
                "size":{
                  "width":769,
                  "height":77},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u8.png"}},
{
          "id":"8b59edfe6b7a4be3897dabefc30d0ad6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":113},
            "size":{
              "width":769,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08676832a846499db727e98ec30d629c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":113},
                "size":{
                  "width":769,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u10.png"}},
{
          "id":"d97e8fd813584127b08e16227a10102f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":113},
            "size":{
              "width":100,
              "height":72},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"114f5c5592f04b27b8d9778ced0f7e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":113},
                "size":{
                  "width":100,
                  "height":72},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u12.png"}},
{
          "id":"342752db4e5948b3a181c146d4c9f510",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":408,
              "y":143},
            "size":{
              "width":73,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7ab13f514143da8b825c8720ef87ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":408,
                  "y":143},
                "size":{
                  "width":73,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5f6f674993642388dfd22e8191b1842",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":1090},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27fe88465c3d46f2a01a19c161a2f288",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":1090},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导诊（pad）/u16.png"}},
{
          "id":"50fceebb844f4116a69df3e097480486",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":420,
              "y":1119},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bf6860115a84e288e12e176a64af2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":1119},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dea84262dbc4425788a32de33665f812",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":144},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d902b77094a44819b6f1648a0d42f67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":144},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 导诊（pad）",
                      "target":{
                        "targetType":"page",
                        "url":"导诊（pad）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/输入个人信息/u16.png"}},
{
          "id":"b3f651f54f3f4cfdb48988de5809e225",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":330},
            "size":{
              "width":600,
              "height":380},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d526ab0bef54d83bc44f70c1424a32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":330},
                "size":{
                  "width":600,
                  "height":380},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入个人信息_1/u18.png"}},
{
          "id":"8e7df591be114085b0503f0af793e851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":385,
              "y":352},
            "size":{
              "width":127,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d18fcc58cd541b0a6e581948ba3f9ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":385,
                  "y":352},
                "size":{
                  "width":127,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78217b6e86ef4fed9aff62068d7c0ed2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":239.5,
              "y":400},
            "size":{
              "width":410,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a331694c8433409da2b1603669bbd758",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "size":{
                  "width":410,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1775a1a884044ea6951aa329a1637baf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":410,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/输入个人信息/u36.png"}}]},
{
          "id":"ac2273b5f8c3472e9fb717e42128e900",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":240,
              "y":630},
            "size":{
              "width":410,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择房间",
                      "target":{
                        "targetType":"page",
                        "url":"选择房间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"38990ce3436c42fcb8600ec5a14fc66a",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "location":{
              "x":240,
              "y":471},
            "size":{
              "width":410,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0faa4e88584ee3910a4bf795dd1630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":471},
                "size":{
                  "width":410,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"ad0799c04df142cbb1ccbfcd94cb0f46",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "location":{
              "x":240,
              "y":540},
            "size":{
              "width":410,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97f353c91f23482b8104ae6bd6e29398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":540},
                "size":{
                  "width":410,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"cf043a7b925a44c199d08f68ecf4ac12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":440,
              "y":510},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e32e3ce29864c7eac4584c47ff3d80e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":440,
                  "y":510},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入个人信息/u61.png"}},
{
          "id":"ddd5fe92093442aeb81c910aa14270e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":500},
            "size":{
              "width":118,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc09d690d38546ce8befe99dbeec9cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":500},
                "size":{
                  "width":118,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37f19fe106614c08b38d4b0412f2d10f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":570},
            "size":{
              "width":79,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf56b25eefe41e5ad319252aaa318f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":570},
                "size":{
                  "width":79,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7aae74b4b9264b7e8048db8d442c11de":{
      "scriptId":"u0"},
    "4f83ec0768ed4e1f9d489422a5e79df2":{
      "scriptId":"u1"},
    "77b283ab6e394761b9240d4093b61e20":{
      "scriptId":"u2"},
    "2768c32ff8a548e898d387e9a0a22170":{
      "scriptId":"u3"},
    "11fa37bf5610496289079fc21c6dd6cb":{
      "scriptId":"u4"},
    "9f81aa683cc84c028a7e7d597c37ee62":{
      "scriptId":"u5"},
    "8b59edfe6b7a4be3897dabefc30d0ad6":{
      "scriptId":"u6"},
    "08676832a846499db727e98ec30d629c":{
      "scriptId":"u7"},
    "d97e8fd813584127b08e16227a10102f":{
      "scriptId":"u8"},
    "114f5c5592f04b27b8d9778ced0f7e05":{
      "scriptId":"u9"},
    "342752db4e5948b3a181c146d4c9f510":{
      "scriptId":"u10"},
    "fe7ab13f514143da8b825c8720ef87ec":{
      "scriptId":"u11"},
    "e5f6f674993642388dfd22e8191b1842":{
      "scriptId":"u12"},
    "27fe88465c3d46f2a01a19c161a2f288":{
      "scriptId":"u13"},
    "50fceebb844f4116a69df3e097480486":{
      "scriptId":"u14"},
    "9bf6860115a84e288e12e176a64af2a1":{
      "scriptId":"u15"},
    "dea84262dbc4425788a32de33665f812":{
      "scriptId":"u16"},
    "d902b77094a44819b6f1648a0d42f67c":{
      "scriptId":"u17"},
    "b3f651f54f3f4cfdb48988de5809e225":{
      "scriptId":"u18"},
    "2d526ab0bef54d83bc44f70c1424a32a":{
      "scriptId":"u19"},
    "8e7df591be114085b0503f0af793e851":{
      "scriptId":"u20"},
    "8d18fcc58cd541b0a6e581948ba3f9ff":{
      "scriptId":"u21"},
    "78217b6e86ef4fed9aff62068d7c0ed2":{
      "scriptId":"u22"},
    "a331694c8433409da2b1603669bbd758":{
      "scriptId":"u23"},
    "1775a1a884044ea6951aa329a1637baf":{
      "scriptId":"u24"},
    "ac2273b5f8c3472e9fb717e42128e900":{
      "scriptId":"u25"},
    "38990ce3436c42fcb8600ec5a14fc66a":{
      "scriptId":"u26"},
    "aa0faa4e88584ee3910a4bf795dd1630":{
      "scriptId":"u27"},
    "ad0799c04df142cbb1ccbfcd94cb0f46":{
      "scriptId":"u28"},
    "97f353c91f23482b8104ae6bd6e29398":{
      "scriptId":"u29"},
    "cf043a7b925a44c199d08f68ecf4ac12":{
      "scriptId":"u30"},
    "6e32e3ce29864c7eac4584c47ff3d80e":{
      "scriptId":"u31"},
    "ddd5fe92093442aeb81c910aa14270e5":{
      "scriptId":"u32"},
    "bc09d690d38546ce8befe99dbeec9cab":{
      "scriptId":"u33"},
    "37f19fe106614c08b38d4b0412f2d10f":{
      "scriptId":"u34"},
    "baf56b25eefe41e5ad319252aaa318f6":{
      "scriptId":"u35"}}});